-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "AuditAction" ADD VALUE 'SESSION_REFRESH';
ALTER TYPE "AuditAction" ADD VALUE 'SESSION_EXPIRE';
ALTER TYPE "AuditAction" ADD VALUE 'SESSION_REVOKE';
ALTER TYPE "AuditAction" ADD VALUE 'PASSWORD_RESET_REQUEST';
ALTER TYPE "AuditAction" ADD VALUE 'PASSWORD_RESET_COMPLETE';
ALTER TYPE "AuditAction" ADD VALUE 'PASSWORD_FORCE_RESET';
ALTER TYPE "AuditAction" ADD VALUE 'EMAIL_CHANGE';
ALTER TYPE "AuditAction" ADD VALUE 'USERNAME_CHANGE';
ALTER TYPE "AuditAction" ADD VALUE 'PROFILE_CHANGE';
ALTER TYPE "AuditAction" ADD VALUE 'ROLE_CHANGE';
ALTER TYPE "AuditAction" ADD VALUE 'PERMISSION_UPDATE';
ALTER TYPE "AuditAction" ADD VALUE 'GROUP_ASSIGN';
ALTER TYPE "AuditAction" ADD VALUE 'GROUP_REMOVE';
ALTER TYPE "AuditAction" ADD VALUE 'PERMISSION_ADD_TO_GROUP';
ALTER TYPE "AuditAction" ADD VALUE 'PERMISSION_REMOVE_FROM_GROUP';
ALTER TYPE "AuditAction" ADD VALUE 'STOCK_ENTRY';
ALTER TYPE "AuditAction" ADD VALUE 'STOCK_EXIT';
ALTER TYPE "AuditAction" ADD VALUE 'STOCK_TRANSFER';
ALTER TYPE "AuditAction" ADD VALUE 'ORDER_CREATE';
ALTER TYPE "AuditAction" ADD VALUE 'ORDER_CANCEL';
ALTER TYPE "AuditAction" ADD VALUE 'RESERVATION_CREATE';
ALTER TYPE "AuditAction" ADD VALUE 'RESERVATION_RELEASE';
ALTER TYPE "AuditAction" ADD VALUE 'EMPLOYEE_HIRE';
ALTER TYPE "AuditAction" ADD VALUE 'EMPLOYEE_TERMINATE';
ALTER TYPE "AuditAction" ADD VALUE 'EMPLOYEE_TRANSFER';
ALTER TYPE "AuditAction" ADD VALUE 'EMPLOYEE_LINK_USER';
ALTER TYPE "AuditAction" ADD VALUE 'CLOCK_IN';
ALTER TYPE "AuditAction" ADD VALUE 'CLOCK_OUT';
ALTER TYPE "AuditAction" ADD VALUE 'TIME_CALCULATE';
ALTER TYPE "AuditAction" ADD VALUE 'TIME_BANK_CREDIT';
ALTER TYPE "AuditAction" ADD VALUE 'TIME_BANK_DEBIT';
ALTER TYPE "AuditAction" ADD VALUE 'TIME_BANK_ADJUST';
ALTER TYPE "AuditAction" ADD VALUE 'ABSENCE_REQUEST';
ALTER TYPE "AuditAction" ADD VALUE 'ABSENCE_APPROVE';
ALTER TYPE "AuditAction" ADD VALUE 'ABSENCE_REJECT';
ALTER TYPE "AuditAction" ADD VALUE 'ABSENCE_CANCEL';
ALTER TYPE "AuditAction" ADD VALUE 'VACATION_SCHEDULE';
ALTER TYPE "AuditAction" ADD VALUE 'VACATION_START';
ALTER TYPE "AuditAction" ADD VALUE 'VACATION_COMPLETE';
ALTER TYPE "AuditAction" ADD VALUE 'VACATION_CANCEL';
ALTER TYPE "AuditAction" ADD VALUE 'VACATION_SELL';
ALTER TYPE "AuditAction" ADD VALUE 'OVERTIME_REQUEST';
ALTER TYPE "AuditAction" ADD VALUE 'OVERTIME_APPROVE';
ALTER TYPE "AuditAction" ADD VALUE 'PAYROLL_CREATE';
ALTER TYPE "AuditAction" ADD VALUE 'PAYROLL_CALCULATE';
ALTER TYPE "AuditAction" ADD VALUE 'PAYROLL_APPROVE';
ALTER TYPE "AuditAction" ADD VALUE 'PAYROLL_CANCEL';
ALTER TYPE "AuditAction" ADD VALUE 'PAYROLL_PAY';
ALTER TYPE "AuditAction" ADD VALUE 'REQUEST_CREATE';
ALTER TYPE "AuditAction" ADD VALUE 'REQUEST_ASSIGN';
ALTER TYPE "AuditAction" ADD VALUE 'REQUEST_COMPLETE';
ALTER TYPE "AuditAction" ADD VALUE 'REQUEST_CANCEL';
ALTER TYPE "AuditAction" ADD VALUE 'REQUEST_COMMENT';
ALTER TYPE "AuditAction" ADD VALUE 'REQUEST_INFO';
ALTER TYPE "AuditAction" ADD VALUE 'REQUEST_INFO_PROVIDE';
ALTER TYPE "AuditAction" ADD VALUE 'NOTIFICATION_SEND';
ALTER TYPE "AuditAction" ADD VALUE 'NOTIFICATION_READ';
ALTER TYPE "AuditAction" ADD VALUE 'NOTIFICATION_DELETE';
ALTER TYPE "AuditAction" ADD VALUE 'CHECK_CPF';
ALTER TYPE "AuditAction" ADD VALUE 'CHECK_CNPJ';

-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "AuditEntity" ADD VALUE 'USER_EMAIL';
ALTER TYPE "AuditEntity" ADD VALUE 'USER_PASSWORD';
ALTER TYPE "AuditEntity" ADD VALUE 'USER_USERNAME';
ALTER TYPE "AuditEntity" ADD VALUE 'USER_ROLE';
ALTER TYPE "AuditEntity" ADD VALUE 'COMPANY';
ALTER TYPE "AuditEntity" ADD VALUE 'COMPANY_ADDRESS';
ALTER TYPE "AuditEntity" ADD VALUE 'COMPANY_CNAE';
ALTER TYPE "AuditEntity" ADD VALUE 'COMPANY_FISCAL_SETTINGS';
ALTER TYPE "AuditEntity" ADD VALUE 'COMPANY_STAKEHOLDER';
ALTER TYPE "AuditEntity" ADD VALUE 'VACATION_BALANCE';
