import type { PrismaClient } from '../generated/prisma/client.js';

interface AccountSeedData {
  code: string;
  name: string;
  type: 'ASSET' | 'LIABILITY' | 'EQUITY' | 'REVENUE' | 'EXPENSE';
  class: 'CURRENT' | 'NON_CURRENT' | 'OPERATIONAL' | 'FINANCIAL' | 'OTHER';
  nature: 'DEBIT' | 'CREDIT';
  parentCode?: string;
}

const STANDARD_BRAZILIAN_CHART: AccountSeedData[] = [
  // 1 - Ativo
  {
    code: '1',
    name: 'Ativo',
    type: 'ASSET',
    class: 'CURRENT',
    nature: 'DEBIT',
  },
  {
    code: '1.1',
    name: 'Ativo Circulante',
    type: 'ASSET',
    class: 'CURRENT',
    nature: 'DEBIT',
    parentCode: '1',
  },
  {
    code: '1.1.1',
    name: 'Caixa e Equivalentes de Caixa',
    type: 'ASSET',
    class: 'CURRENT',
    nature: 'DEBIT',
    parentCode: '1.1',
  },
  {
    code: '1.1.1.01',
    name: 'Caixa Geral',
    type: 'ASSET',
    class: 'CURRENT',
    nature: 'DEBIT',
    parentCode: '1.1.1',
  },
  {
    code: '1.1.1.02',
    name: 'Bancos Conta Movimento',
    type: 'ASSET',
    class: 'CURRENT',
    nature: 'DEBIT',
    parentCode: '1.1.1',
  },
  {
    code: '1.1.1.03',
    name: 'Aplicações Financeiras de Liquidez Imediata',
    type: 'ASSET',
    class: 'CURRENT',
    nature: 'DEBIT',
    parentCode: '1.1.1',
  },
  {
    code: '1.1.2',
    name: 'Contas a Receber',
    type: 'ASSET',
    class: 'CURRENT',
    nature: 'DEBIT',
    parentCode: '1.1',
  },
  {
    code: '1.1.2.01',
    name: 'Clientes',
    type: 'ASSET',
    class: 'CURRENT',
    nature: 'DEBIT',
    parentCode: '1.1.2',
  },
  {
    code: '1.1.2.02',
    name: 'Duplicatas a Receber',
    type: 'ASSET',
    class: 'CURRENT',
    nature: 'DEBIT',
    parentCode: '1.1.2',
  },
  {
    code: '1.1.2.03',
    name: '(-) Provisão para Devedores Duvidosos',
    type: 'ASSET',
    class: 'CURRENT',
    nature: 'DEBIT',
    parentCode: '1.1.2',
  },
  {
    code: '1.1.3',
    name: 'Estoques',
    type: 'ASSET',
    class: 'CURRENT',
    nature: 'DEBIT',
    parentCode: '1.1',
  },
  {
    code: '1.1.3.01',
    name: 'Mercadorias para Revenda',
    type: 'ASSET',
    class: 'CURRENT',
    nature: 'DEBIT',
    parentCode: '1.1.3',
  },
  {
    code: '1.1.3.02',
    name: 'Matérias-Primas',
    type: 'ASSET',
    class: 'CURRENT',
    nature: 'DEBIT',
    parentCode: '1.1.3',
  },
  {
    code: '1.1.3.03',
    name: 'Produtos em Elaboração',
    type: 'ASSET',
    class: 'CURRENT',
    nature: 'DEBIT',
    parentCode: '1.1.3',
  },
  {
    code: '1.1.3.04',
    name: 'Produtos Acabados',
    type: 'ASSET',
    class: 'CURRENT',
    nature: 'DEBIT',
    parentCode: '1.1.3',
  },
  {
    code: '1.1.4',
    name: 'Tributos a Recuperar',
    type: 'ASSET',
    class: 'CURRENT',
    nature: 'DEBIT',
    parentCode: '1.1',
  },
  {
    code: '1.1.4.01',
    name: 'ICMS a Recuperar',
    type: 'ASSET',
    class: 'CURRENT',
    nature: 'DEBIT',
    parentCode: '1.1.4',
  },
  {
    code: '1.1.4.02',
    name: 'PIS a Recuperar',
    type: 'ASSET',
    class: 'CURRENT',
    nature: 'DEBIT',
    parentCode: '1.1.4',
  },
  {
    code: '1.1.4.03',
    name: 'COFINS a Recuperar',
    type: 'ASSET',
    class: 'CURRENT',
    nature: 'DEBIT',
    parentCode: '1.1.4',
  },
  {
    code: '1.2',
    name: 'Ativo Não Circulante',
    type: 'ASSET',
    class: 'NON_CURRENT',
    nature: 'DEBIT',
    parentCode: '1',
  },
  {
    code: '1.2.1',
    name: 'Imobilizado',
    type: 'ASSET',
    class: 'NON_CURRENT',
    nature: 'DEBIT',
    parentCode: '1.2',
  },
  {
    code: '1.2.1.01',
    name: 'Máquinas e Equipamentos',
    type: 'ASSET',
    class: 'NON_CURRENT',
    nature: 'DEBIT',
    parentCode: '1.2.1',
  },
  {
    code: '1.2.1.02',
    name: 'Móveis e Utensílios',
    type: 'ASSET',
    class: 'NON_CURRENT',
    nature: 'DEBIT',
    parentCode: '1.2.1',
  },
  {
    code: '1.2.1.03',
    name: 'Veículos',
    type: 'ASSET',
    class: 'NON_CURRENT',
    nature: 'DEBIT',
    parentCode: '1.2.1',
  },
  {
    code: '1.2.1.04',
    name: '(-) Depreciação Acumulada',
    type: 'ASSET',
    class: 'NON_CURRENT',
    nature: 'DEBIT',
    parentCode: '1.2.1',
  },
  {
    code: '1.2.2',
    name: 'Intangível',
    type: 'ASSET',
    class: 'NON_CURRENT',
    nature: 'DEBIT',
    parentCode: '1.2',
  },
  {
    code: '1.2.2.01',
    name: 'Marcas e Patentes',
    type: 'ASSET',
    class: 'NON_CURRENT',
    nature: 'DEBIT',
    parentCode: '1.2.2',
  },
  {
    code: '1.2.2.02',
    name: 'Softwares',
    type: 'ASSET',
    class: 'NON_CURRENT',
    nature: 'DEBIT',
    parentCode: '1.2.2',
  },

  // 2 - Passivo
  {
    code: '2',
    name: 'Passivo',
    type: 'LIABILITY',
    class: 'CURRENT',
    nature: 'CREDIT',
  },
  {
    code: '2.1',
    name: 'Passivo Circulante',
    type: 'LIABILITY',
    class: 'CURRENT',
    nature: 'CREDIT',
    parentCode: '2',
  },
  {
    code: '2.1.1',
    name: 'Fornecedores',
    type: 'LIABILITY',
    class: 'CURRENT',
    nature: 'CREDIT',
    parentCode: '2.1',
  },
  {
    code: '2.1.1.01',
    name: 'Fornecedores Nacionais',
    type: 'LIABILITY',
    class: 'CURRENT',
    nature: 'CREDIT',
    parentCode: '2.1.1',
  },
  {
    code: '2.1.1.02',
    name: 'Fornecedores Estrangeiros',
    type: 'LIABILITY',
    class: 'CURRENT',
    nature: 'CREDIT',
    parentCode: '2.1.1',
  },
  {
    code: '2.1.2',
    name: 'Obrigações Trabalhistas',
    type: 'LIABILITY',
    class: 'CURRENT',
    nature: 'CREDIT',
    parentCode: '2.1',
  },
  {
    code: '2.1.2.01',
    name: 'Salários a Pagar',
    type: 'LIABILITY',
    class: 'CURRENT',
    nature: 'CREDIT',
    parentCode: '2.1.2',
  },
  {
    code: '2.1.2.02',
    name: 'FGTS a Recolher',
    type: 'LIABILITY',
    class: 'CURRENT',
    nature: 'CREDIT',
    parentCode: '2.1.2',
  },
  {
    code: '2.1.2.03',
    name: 'INSS a Recolher',
    type: 'LIABILITY',
    class: 'CURRENT',
    nature: 'CREDIT',
    parentCode: '2.1.2',
  },
  {
    code: '2.1.3',
    name: 'Obrigações Fiscais',
    type: 'LIABILITY',
    class: 'CURRENT',
    nature: 'CREDIT',
    parentCode: '2.1',
  },
  {
    code: '2.1.3.01',
    name: 'ICMS a Recolher',
    type: 'LIABILITY',
    class: 'CURRENT',
    nature: 'CREDIT',
    parentCode: '2.1.3',
  },
  {
    code: '2.1.3.02',
    name: 'PIS a Recolher',
    type: 'LIABILITY',
    class: 'CURRENT',
    nature: 'CREDIT',
    parentCode: '2.1.3',
  },
  {
    code: '2.1.3.03',
    name: 'COFINS a Recolher',
    type: 'LIABILITY',
    class: 'CURRENT',
    nature: 'CREDIT',
    parentCode: '2.1.3',
  },
  {
    code: '2.1.3.04',
    name: 'IRPJ a Recolher',
    type: 'LIABILITY',
    class: 'CURRENT',
    nature: 'CREDIT',
    parentCode: '2.1.3',
  },
  {
    code: '2.2',
    name: 'Passivo Não Circulante',
    type: 'LIABILITY',
    class: 'NON_CURRENT',
    nature: 'CREDIT',
    parentCode: '2',
  },
  {
    code: '2.2.1',
    name: 'Empréstimos e Financiamentos LP',
    type: 'LIABILITY',
    class: 'NON_CURRENT',
    nature: 'CREDIT',
    parentCode: '2.2',
  },
  {
    code: '2.2.1.01',
    name: 'Empréstimos Bancários LP',
    type: 'LIABILITY',
    class: 'NON_CURRENT',
    nature: 'CREDIT',
    parentCode: '2.2.1',
  },

  // 3 - Patrimônio Líquido
  {
    code: '3',
    name: 'Patrimônio Líquido',
    type: 'EQUITY',
    class: 'OTHER',
    nature: 'CREDIT',
  },
  {
    code: '3.1',
    name: 'Capital Social',
    type: 'EQUITY',
    class: 'OTHER',
    nature: 'CREDIT',
    parentCode: '3',
  },
  {
    code: '3.1.1',
    name: 'Capital Social Subscrito',
    type: 'EQUITY',
    class: 'OTHER',
    nature: 'CREDIT',
    parentCode: '3.1',
  },
  {
    code: '3.1.2',
    name: '(-) Capital Social a Integralizar',
    type: 'EQUITY',
    class: 'OTHER',
    nature: 'CREDIT',
    parentCode: '3.1',
  },
  {
    code: '3.2',
    name: 'Reservas',
    type: 'EQUITY',
    class: 'OTHER',
    nature: 'CREDIT',
    parentCode: '3',
  },
  {
    code: '3.2.1',
    name: 'Reserva Legal',
    type: 'EQUITY',
    class: 'OTHER',
    nature: 'CREDIT',
    parentCode: '3.2',
  },
  {
    code: '3.2.2',
    name: 'Reserva Estatutária',
    type: 'EQUITY',
    class: 'OTHER',
    nature: 'CREDIT',
    parentCode: '3.2',
  },
  {
    code: '3.3',
    name: 'Lucros/Prejuízos Acumulados',
    type: 'EQUITY',
    class: 'OTHER',
    nature: 'CREDIT',
    parentCode: '3',
  },
  {
    code: '3.3.1',
    name: 'Lucros Acumulados',
    type: 'EQUITY',
    class: 'OTHER',
    nature: 'CREDIT',
    parentCode: '3.3',
  },
  {
    code: '3.3.2',
    name: 'Prejuízos Acumulados',
    type: 'EQUITY',
    class: 'OTHER',
    nature: 'CREDIT',
    parentCode: '3.3',
  },

  // 4 - Receitas
  {
    code: '4',
    name: 'Receitas',
    type: 'REVENUE',
    class: 'OPERATIONAL',
    nature: 'CREDIT',
  },
  {
    code: '4.1',
    name: 'Receita Operacional',
    type: 'REVENUE',
    class: 'OPERATIONAL',
    nature: 'CREDIT',
    parentCode: '4',
  },
  {
    code: '4.1.1',
    name: 'Receita de Vendas de Produtos',
    type: 'REVENUE',
    class: 'OPERATIONAL',
    nature: 'CREDIT',
    parentCode: '4.1',
  },
  {
    code: '4.1.2',
    name: 'Receita de Prestação de Serviços',
    type: 'REVENUE',
    class: 'OPERATIONAL',
    nature: 'CREDIT',
    parentCode: '4.1',
  },
  {
    code: '4.1.3',
    name: '(-) Deduções da Receita Bruta',
    type: 'REVENUE',
    class: 'OPERATIONAL',
    nature: 'CREDIT',
    parentCode: '4.1',
  },
  {
    code: '4.2',
    name: 'Receita Financeira',
    type: 'REVENUE',
    class: 'FINANCIAL',
    nature: 'CREDIT',
    parentCode: '4',
  },
  {
    code: '4.2.1',
    name: 'Juros Recebidos',
    type: 'REVENUE',
    class: 'FINANCIAL',
    nature: 'CREDIT',
    parentCode: '4.2',
  },
  {
    code: '4.2.2',
    name: 'Rendimentos de Aplicações',
    type: 'REVENUE',
    class: 'FINANCIAL',
    nature: 'CREDIT',
    parentCode: '4.2',
  },
  {
    code: '4.3',
    name: 'Outras Receitas',
    type: 'REVENUE',
    class: 'OTHER',
    nature: 'CREDIT',
    parentCode: '4',
  },
  {
    code: '4.3.1',
    name: 'Ganhos de Capital',
    type: 'REVENUE',
    class: 'OTHER',
    nature: 'CREDIT',
    parentCode: '4.3',
  },

  // 5 - Despesas
  {
    code: '5',
    name: 'Despesas',
    type: 'EXPENSE',
    class: 'OPERATIONAL',
    nature: 'DEBIT',
  },
  {
    code: '5.1',
    name: 'Custos Operacionais',
    type: 'EXPENSE',
    class: 'OPERATIONAL',
    nature: 'DEBIT',
    parentCode: '5',
  },
  {
    code: '5.1.1',
    name: 'Custo das Mercadorias Vendidas (CMV)',
    type: 'EXPENSE',
    class: 'OPERATIONAL',
    nature: 'DEBIT',
    parentCode: '5.1',
  },
  {
    code: '5.1.2',
    name: 'Custo dos Serviços Prestados (CSP)',
    type: 'EXPENSE',
    class: 'OPERATIONAL',
    nature: 'DEBIT',
    parentCode: '5.1',
  },
  {
    code: '5.2',
    name: 'Despesas Administrativas',
    type: 'EXPENSE',
    class: 'OPERATIONAL',
    nature: 'DEBIT',
    parentCode: '5',
  },
  {
    code: '5.2.1',
    name: 'Salários e Encargos',
    type: 'EXPENSE',
    class: 'OPERATIONAL',
    nature: 'DEBIT',
    parentCode: '5.2',
  },
  {
    code: '5.2.2',
    name: 'Aluguel',
    type: 'EXPENSE',
    class: 'OPERATIONAL',
    nature: 'DEBIT',
    parentCode: '5.2',
  },
  {
    code: '5.2.3',
    name: 'Energia Elétrica',
    type: 'EXPENSE',
    class: 'OPERATIONAL',
    nature: 'DEBIT',
    parentCode: '5.2',
  },
  {
    code: '5.2.4',
    name: 'Material de Escritório',
    type: 'EXPENSE',
    class: 'OPERATIONAL',
    nature: 'DEBIT',
    parentCode: '5.2',
  },
  {
    code: '5.2.5',
    name: 'Depreciação',
    type: 'EXPENSE',
    class: 'OPERATIONAL',
    nature: 'DEBIT',
    parentCode: '5.2',
  },
  {
    code: '5.3',
    name: 'Despesas Financeiras',
    type: 'EXPENSE',
    class: 'FINANCIAL',
    nature: 'DEBIT',
    parentCode: '5',
  },
  {
    code: '5.3.1',
    name: 'Juros Pagos',
    type: 'EXPENSE',
    class: 'FINANCIAL',
    nature: 'DEBIT',
    parentCode: '5.3',
  },
  {
    code: '5.3.2',
    name: 'Tarifas Bancárias',
    type: 'EXPENSE',
    class: 'FINANCIAL',
    nature: 'DEBIT',
    parentCode: '5.3',
  },
  {
    code: '5.3.3',
    name: 'Multas e Juros de Mora',
    type: 'EXPENSE',
    class: 'FINANCIAL',
    nature: 'DEBIT',
    parentCode: '5.3',
  },
  {
    code: '5.4',
    name: 'Impostos e Taxas',
    type: 'EXPENSE',
    class: 'OPERATIONAL',
    nature: 'DEBIT',
    parentCode: '5',
  },
  {
    code: '5.4.1',
    name: 'IRPJ',
    type: 'EXPENSE',
    class: 'OPERATIONAL',
    nature: 'DEBIT',
    parentCode: '5.4',
  },
  {
    code: '5.4.2',
    name: 'CSLL',
    type: 'EXPENSE',
    class: 'OPERATIONAL',
    nature: 'DEBIT',
    parentCode: '5.4',
  },
  {
    code: '5.4.3',
    name: 'PIS/COFINS',
    type: 'EXPENSE',
    class: 'OPERATIONAL',
    nature: 'DEBIT',
    parentCode: '5.4',
  },
];

export async function seedChartOfAccounts(
  prisma: PrismaClient,
  tenantId: string,
) {
  const existingCount = await prisma.chartOfAccount.count({
    where: { tenantId },
  });

  if (existingCount > 0) {
    console.log(
      `  [Chart of Accounts] Tenant ${tenantId} already has ${existingCount} accounts, skipping seed.`,
    );
    return;
  }

  console.log(
    `  [Chart of Accounts] Seeding ${STANDARD_BRAZILIAN_CHART.length} accounts for tenant ${tenantId}...`,
  );

  // First pass: create all accounts without parent references
  const codeToIdMap = new Map<string, string>();

  for (const accountData of STANDARD_BRAZILIAN_CHART) {
    const created = await prisma.chartOfAccount.create({
      data: {
        tenantId,
        code: accountData.code,
        name: accountData.name,
        type: accountData.type,
        class: accountData.class,
        nature: accountData.nature,
        isActive: true,
        isSystem: true,
      },
    });
    codeToIdMap.set(accountData.code, created.id);
  }

  // Second pass: set parent references
  for (const accountData of STANDARD_BRAZILIAN_CHART) {
    if (accountData.parentCode) {
      const accountId = codeToIdMap.get(accountData.code);
      const parentId = codeToIdMap.get(accountData.parentCode);
      if (accountId && parentId) {
        await prisma.chartOfAccount.update({
          where: { id: accountId },
          data: { parentId },
        });
      }
    }
  }

  console.log(
    `  [Chart of Accounts] Seeded ${STANDARD_BRAZILIAN_CHART.length} accounts successfully.`,
  );
}
