/**
 * eSocial Tabela 01 — Categorias de Trabalhador
 * Fonte: Manual do eSocial v. S-1.2
 */
export const CATEGORIAS_TRABALHADOR = [
  { code: '101', description: 'Empregado - Geral, inclusive o empregado público da administração direta ou indireta contratado pela CLT' },
  { code: '102', description: 'Empregado - Trabalhador Rural por Pequeno Prazo da Lei 11.718/2008' },
  { code: '103', description: 'Empregado - Aprendiz (Lei 10.097/2000), inclusive o aprendiz contratado nos termos do art. 428-A da CLT' },
  { code: '104', description: 'Empregado - Doméstico' },
  { code: '105', description: 'Empregado - Contrato a termo firmado nos termos da Lei 9.601/1998' },
  { code: '106', description: 'Trabalhador Temporário - contrato nos termos da Lei 6.019/1974' },
  { code: '107', description: 'Empregado - Contrato de trabalho Verde e Amarelo - Lei 13.874/2019' },
  { code: '108', description: 'Empregado - Contrato de trabalho intermitente' },
  { code: '111', description: 'Empregado - Contrato de trabalho do Programa Mais Empregos' },
  { code: '201', description: 'Trabalhador Avulso Portuário' },
  { code: '202', description: 'Trabalhador Avulso Não Portuário' },
  { code: '301', description: 'Servidor Público - Titular de Cargo Efetivo, Magistrado, Ministro de Tribunal de Contas, Conselheiro de Tribunal de Contas e Membro do Ministério Público' },
  { code: '302', description: 'Servidor Público - Ocupante de Cargo Exclusivo em Comissão' },
  { code: '303', description: 'Agente Político' },
  { code: '305', description: 'Servidor Público indicado para conselho ou órgão deliberativo, na condição de representante do governo, órgão ou entidade da administração pública' },
  { code: '306', description: 'Servidor Público - Contratado por Tempo Determinado' },
  { code: '309', description: 'Agente Público - Outros' },
  { code: '401', description: 'Dirigente Sindical - em relação a remuneração recebida no sindicato' },
  { code: '410', description: 'Trabalhador cedido - informação prestada pelo cessionário' },
  { code: '501', description: 'Contribuinte Individual - Autônomo em geral, inclusive o operador de máquina, com contribuição sobre remuneração' },
  { code: '701', description: 'Contribuinte Individual - Autônomo em geral, inclusive o operador de máquina, sem contribuição sobre remuneração' },
  { code: '711', description: 'Contribuinte Individual - Transportador autônomo de passageiros' },
  { code: '712', description: 'Contribuinte Individual - Transportador autônomo de carga' },
  { code: '721', description: 'Contribuinte Individual - Diretor não empregado com FGTS' },
  { code: '722', description: 'Contribuinte Individual - Diretor não empregado sem FGTS' },
  { code: '723', description: 'Contribuinte Individual - Empresário, sócio e membro de conselho de administração ou fiscal' },
  { code: '731', description: 'Contribuinte Individual - Cooperado que presta serviços por intermédio de cooperativa de trabalho' },
  { code: '734', description: 'Contribuinte Individual - Transportador Cooperado que presta serviços por intermédio de cooperativa de trabalho' },
  { code: '738', description: 'Contribuinte Individual - Cooperado filiado a cooperativa de produção' },
  { code: '741', description: 'Contribuinte Individual - Microempreendedor Individual (MEI)' },
  { code: '751', description: 'Contribuinte Individual - Magistrado classista temporário da Justiça do Trabalho' },
  { code: '761', description: 'Contribuinte Individual - Associado eleito para direção de cooperativa, associação ou entidade de classe' },
  { code: '771', description: 'Contribuinte Individual - Membro de conselho tutelar' },
  { code: '781', description: 'Ministro de confissão religiosa ou membro de vida consagrada, de congregação ou de ordem religiosa' },
  { code: '901', description: 'Estagiário' },
  { code: '902', description: 'Médico Residente' },
  { code: '903', description: 'Bolsista, nos termos da Lei 8.958/1994' },
  { code: '904', description: 'Participante de curso de formação, como combatente de incêndio florestal' },
  { code: '905', description: 'Atleta não profissional em formação que receba bolsa' },
];
