/**
 * eSocial Tabela 03 — Natureza das Rubricas da Folha de Pagamento
 * Fonte: Manual do eSocial v. S-1.2
 * Seleção dos códigos mais utilizados.
 */
export const NATUREZAS_RUBRICA = [
  { code: '1000', description: 'Salário, vencimento, soldo ou subsídio' },
  { code: '1002', description: 'Salário Mínimo Legal ou Piso Salarial' },
  { code: '1003', description: 'Remuneração por hora extra' },
  { code: '1004', description: 'Adicional de insalubridade' },
  { code: '1005', description: 'Adicional de periculosidade' },
  { code: '1006', description: 'Adicional noturno' },
  { code: '1007', description: 'Adicional de transferência' },
  { code: '1009', description: 'Salário-família' },
  { code: '1010', description: 'Salário in natura / Utilidades' },
  { code: '1011', description: 'Adicional a título de substituição / Acúmulo de função' },
  { code: '1020', description: 'Comissões' },
  { code: '1021', description: 'Gratificações' },
  { code: '1023', description: 'Gorjeta' },
  { code: '1024', description: 'Quebra de caixa' },
  { code: '1040', description: 'Participação nos Lucros e Resultados (PLR)' },
  { code: '1044', description: 'Prêmios' },
  { code: '1045', description: 'Abonos' },
  { code: '1099', description: 'Outras verbas salariais' },
  { code: '1200', description: '13º Salário' },
  { code: '1201', description: '13º Salário - 1ª parcela' },
  { code: '1202', description: '13º Salário - 2ª parcela' },
  { code: '1210', description: 'Férias - gozadas' },
  { code: '1211', description: 'Férias - abono pecuniário' },
  { code: '1212', description: 'Férias - 1/3 constitucional' },
  { code: '1300', description: 'Aviso prévio indenizado' },
  { code: '1350', description: 'Multa do FGTS (40%)' },
  { code: '1401', description: 'Diárias de viagem' },
  { code: '1402', description: 'Ajuda de custo' },
  { code: '1403', description: 'Auxílio-alimentação' },
  { code: '1404', description: 'Auxílio-transporte' },
  { code: '1405', description: 'Auxílio-educação' },
  { code: '1406', description: 'Auxílio-saúde / Plano de saúde' },
  { code: '1407', description: 'Auxílio-moradia' },
  { code: '1409', description: 'Auxílio-creche / Reembolso babá' },
  { code: '1601', description: 'Seguro de vida em grupo' },
  { code: '1800', description: 'Previdência complementar - contribuição do empregador' },
  { code: '5001', description: 'INSS - Desconto do segurado' },
  { code: '5002', description: 'IRRF - Imposto sobre a Renda Retido na Fonte' },
  { code: '5010', description: 'Contribuição Sindical - Empregado' },
  { code: '5050', description: 'Pensão alimentícia' },
  { code: '5099', description: 'Outros descontos' },
  { code: '5501', description: 'Vale-transporte - Desconto' },
  { code: '5502', description: 'Vale-refeição/alimentação - Desconto' },
  { code: '5503', description: 'Plano de saúde - Desconto' },
  { code: '5504', description: 'Previdência complementar - Desconto do empregado' },
  { code: '9200', description: 'Base de cálculo INSS' },
  { code: '9201', description: 'Base de cálculo IRRF' },
  { code: '9202', description: 'Base de cálculo FGTS' },
  { code: '9203', description: 'Base de cálculo 13º Salário (INSS)' },
  { code: '9210', description: 'Base de cálculo Férias (INSS)' },
  { code: '9999', description: 'Informativo - Outros' },
];
