import {
  NotificationChannel,
  NotificationPriority,
  NotificationType,
  type ModuleNotificationManifest,
} from '../public/index.js';

const I = NotificationType.INFORMATIONAL;
const L = NotificationType.LINK;
const AP = NotificationType.APPROVAL;
const IA = NotificationChannel.IN_APP;
const EM = NotificationChannel.EMAIL;

export const salesManifest: ModuleNotificationManifest = {
  module: 'sales',
  displayName: 'Vendas',
  icon: 'ShoppingCart',
  order: 50,
  categories: [
    // Orders
    {
      code: 'sales.order_placed',
      name: 'Pedido recebido',
      description: 'Novo pedido registrado.',
      defaultType: L,
      defaultPriority: NotificationPriority.NORMAL,
      defaultChannels: [IA],
      digestSupported: true,
    },
    {
      code: 'sales.order_from_customer',
      name: 'Pedido do cliente',
      description: 'Pedido vindo do portal do cliente.',
      defaultType: L,
      defaultPriority: NotificationPriority.HIGH,
      defaultChannels: [IA, EM],
    },
    {
      code: 'sales.order_confirmed',
      name: 'Pedido confirmado',
      description: 'Pedido confirmado para produção/expedição.',
      defaultType: L,
      defaultPriority: NotificationPriority.NORMAL,
      defaultChannels: [IA],
    },
    {
      code: 'sales.payment_received',
      name: 'Pagamento recebido',
      description: 'Pagamento do pedido realizado.',
      defaultType: L,
      defaultPriority: NotificationPriority.NORMAL,
      defaultChannels: [IA, EM],
    },
    {
      code: 'sales.order_shipped',
      name: 'Pedido enviado',
      description: 'Pedido despachado.',
      defaultType: L,
      defaultPriority: NotificationPriority.NORMAL,
      defaultChannels: [IA, EM],
    },
    {
      code: 'sales.order_delivered',
      name: 'Pedido entregue',
      description: 'Entrega confirmada.',
      defaultType: L,
      defaultPriority: NotificationPriority.NORMAL,
      defaultChannels: [IA, EM],
    },
    {
      code: 'sales.order_cancelled',
      name: 'Pedido cancelado',
      description: 'Pedido foi cancelado.',
      defaultType: L,
      defaultPriority: NotificationPriority.HIGH,
      defaultChannels: [IA, EM],
    },
    {
      code: 'sales.order_return_initiated',
      name: 'Devolução solicitada',
      description: 'Cliente solicitou devolução.',
      defaultType: L,
      defaultPriority: NotificationPriority.NORMAL,
      defaultChannels: [IA, EM],
    },
    {
      code: 'sales.order_refund_processed',
      name: 'Reembolso processado',
      description: 'Reembolso liberado.',
      defaultType: L,
      defaultPriority: NotificationPriority.NORMAL,
      defaultChannels: [IA, EM],
    },

    // Quotes / proposals
    {
      code: 'sales.quote_created',
      name: 'Orçamento criado',
      description: 'Novo orçamento gerado.',
      defaultType: I,
      defaultPriority: NotificationPriority.NORMAL,
      defaultChannels: [IA],
    },
    {
      code: 'sales.quote_sent',
      name: 'Orçamento enviado',
      description: 'Orçamento enviado para o cliente.',
      defaultType: I,
      defaultPriority: NotificationPriority.NORMAL,
      defaultChannels: [IA],
    },
    {
      code: 'sales.quote_accepted',
      name: 'Orçamento aceito',
      description: 'Cliente aceitou o orçamento.',
      defaultType: L,
      defaultPriority: NotificationPriority.HIGH,
      defaultChannels: [IA, EM],
    },
    {
      code: 'sales.quote_rejected',
      name: 'Orçamento rejeitado',
      description: 'Cliente recusou o orçamento.',
      defaultType: L,
      defaultPriority: NotificationPriority.NORMAL,
      defaultChannels: [IA],
    },
    {
      code: 'sales.quote_expired',
      name: 'Orçamento expirado',
      description: 'Orçamento passou da validade.',
      defaultType: L,
      defaultPriority: NotificationPriority.NORMAL,
      defaultChannels: [IA, EM],
    },
    {
      code: 'sales.quote_approval_required',
      name: 'Orçamento requer aprovação',
      description: 'Valor acima do teto.',
      defaultType: AP,
      defaultPriority: NotificationPriority.HIGH,
      defaultChannels: [IA, EM],
    },

    // CRM deals
    {
      code: 'sales.deal_created',
      name: 'Oportunidade criada',
      description: 'Novo deal no CRM.',
      defaultType: L,
      defaultPriority: NotificationPriority.NORMAL,
      defaultChannels: [IA],
    },
    {
      code: 'sales.deal_stage_changed',
      name: 'Deal mudou de etapa',
      description: 'Deal avançou/recuou no funil.',
      defaultType: I,
      defaultPriority: NotificationPriority.LOW,
      defaultChannels: [IA],
    },
    {
      code: 'sales.deal_won',
      name: 'Deal ganho',
      description: 'Oportunidade fechada com sucesso.',
      defaultType: L,
      defaultPriority: NotificationPriority.HIGH,
      defaultChannels: [IA, EM],
    },
    {
      code: 'sales.deal_lost',
      name: 'Deal perdido',
      description: 'Oportunidade encerrada sem conversão.',
      defaultType: L,
      defaultPriority: NotificationPriority.NORMAL,
      defaultChannels: [IA],
    },
    {
      code: 'sales.deal_stuck',
      name: 'Deal parado há X dias',
      description: 'Deal sem atividade.',
      defaultType: L,
      defaultPriority: NotificationPriority.NORMAL,
      defaultChannels: [IA, EM],
    },

    // Leads
    {
      code: 'sales.lead_assigned',
      name: 'Lead atribuído',
      description: 'Novo lead para você.',
      defaultType: L,
      defaultPriority: NotificationPriority.NORMAL,
      defaultChannels: [IA, EM],
    },
    {
      code: 'sales.lead_high_score',
      name: 'Lead quente',
      description: 'Lead com score alto.',
      defaultType: L,
      defaultPriority: NotificationPriority.HIGH,
      defaultChannels: [IA, EM],
    },
    {
      code: 'sales.lead_inactive',
      name: 'Lead inativo',
      description: 'Lead sem atividade recente.',
      defaultType: L,
      defaultPriority: NotificationPriority.NORMAL,
      defaultChannels: [IA],
    },

    // Reservations
    {
      code: 'sales.reservation_created',
      name: 'Reserva criada',
      description: 'Nova reserva de estoque.',
      defaultType: I,
      defaultPriority: NotificationPriority.NORMAL,
      defaultChannels: [IA],
    },
    {
      code: 'sales.reservation_expiring',
      name: 'Reserva a expirar',
      description: 'Reserva próxima do prazo.',
      defaultType: L,
      defaultPriority: NotificationPriority.HIGH,
      defaultChannels: [IA, EM],
    },
    {
      code: 'sales.reservation_expired',
      name: 'Reserva expirada',
      description: 'Reserva cancelada por prazo.',
      defaultType: L,
      defaultPriority: NotificationPriority.NORMAL,
      defaultChannels: [IA],
    },
    {
      code: 'sales.reservation_confirmed',
      name: 'Reserva confirmada',
      description: 'Reserva foi confirmada.',
      defaultType: I,
      defaultPriority: NotificationPriority.NORMAL,
      defaultChannels: [IA],
    },

    // Commission / customer
    {
      code: 'sales.commission_calculated',
      name: 'Comissão calculada',
      description: 'Sua comissão foi calculada.',
      defaultType: L,
      defaultPriority: NotificationPriority.NORMAL,
      defaultChannels: [IA, EM],
    },
    {
      code: 'sales.commission_paid',
      name: 'Comissão paga',
      description: 'Comissão creditada.',
      defaultType: L,
      defaultPriority: NotificationPriority.NORMAL,
      defaultChannels: [IA, EM],
    },
    {
      code: 'sales.customer_registered',
      name: 'Novo cliente',
      description: 'Cliente registrado.',
      defaultType: L,
      defaultPriority: NotificationPriority.NORMAL,
      defaultChannels: [IA],
    },
    {
      code: 'sales.customer_birthday',
      name: 'Aniversário do cliente',
      description: 'Cliente faz aniversário hoje.',
      defaultType: I,
      defaultPriority: NotificationPriority.LOW,
      defaultChannels: [IA],
    },
    {
      code: 'sales.customer_at_risk',
      name: 'Cliente em risco',
      description: 'Cliente com risco de churn.',
      defaultType: L,
      defaultPriority: NotificationPriority.HIGH,
      defaultChannels: [IA, EM],
    },

    // POS
    {
      code: 'sales.pos_session_opened',
      name: 'Caixa aberto',
      description: 'Sessão de PDV iniciada.',
      defaultType: I,
      defaultPriority: NotificationPriority.LOW,
      defaultChannels: [IA],
    },
    {
      code: 'sales.pos_session_closed',
      name: 'Caixa fechado',
      description: 'Sessão de PDV finalizada.',
      defaultType: I,
      defaultPriority: NotificationPriority.NORMAL,
      defaultChannels: [IA],
    },
    {
      code: 'sales.pos_cash_mismatch',
      name: 'Divergência no caixa',
      description: 'Saldo não bate no fechamento.',
      defaultType: L,
      defaultPriority: NotificationPriority.HIGH,
      defaultChannels: [IA, EM],
    },
    {
      code: 'sales.pos_discount_approval',
      name: 'Desconto requer aprovação',
      description: 'Desconto acima do limite.',
      defaultType: AP,
      defaultPriority: NotificationPriority.HIGH,
      defaultChannels: [IA],
    },

    // Marketplace
    {
      code: 'sales.marketplace_order',
      name: 'Pedido de marketplace',
      description: 'Novo pedido de integração.',
      defaultType: L,
      defaultPriority: NotificationPriority.HIGH,
      defaultChannels: [IA, EM],
    },
    {
      code: 'sales.marketplace_sync_error',
      name: 'Erro na sincronização',
      description: 'Falha ao sincronizar marketplace.',
      defaultType: L,
      defaultPriority: NotificationPriority.HIGH,
      defaultChannels: [IA, EM],
    },
  ],
};
