/**
 * All permissions for E2E tests — single source of truth.
 * Used by vitest-setup-e2e.ts (seed) and create-and-authenticate-user.e2e.ts (specific perms).
 */
export const ALL_PERMISSIONS: Record<string, Record<string, string[]>> = {
  // SELF module (own user permissions)
  self: {
    profile: [
      'read',
      'update',
      'update-email',
      'update-password',
      'update-username',
      'delete',
    ],
    sessions: ['read', 'list', 'revoke'],
    permissions: ['read', 'list'],
    groups: ['read', 'list'],
    audit: ['read', 'list'],
    employee: ['read'],
    'time-entries': ['read', 'list', 'create'],
    schedule: ['read'],
    'time-bank': ['read', 'list'],
    vacations: ['read', 'list', 'request', 'cancel'],
    absences: ['read', 'list', 'request', 'cancel'],
    payslips: ['read', 'list', 'download'],
    overtime: ['read', 'list', 'request'],
  },
  // CORE module
  core: {
    users: ['create', 'read', 'update', 'delete', 'list', 'manage'],
    sessions: ['read', 'delete', 'list', 'revoke', 'revoke-all'],
    profiles: ['read', 'update'],
    'label-templates': [
      'create',
      'read',
      'update',
      'delete',
      'list',
      'duplicate',
      'manage',
    ],
    teams: ['create', 'read', 'update', 'delete', 'list', 'manage'],
    'teams.members': ['add', 'remove', 'manage'],
    'teams.emails': ['link', 'read', 'manage', 'unlink'],
  },
  // STOCK module
  stock: {
    products: [
      'create',
      'read',
      'update',
      'delete',
      'list',
      'request',
      'approve',
      'manage',
      'access',
      'modify',
      'import',
      'register',
      'admin',
      'export',
      'print',
      'remove',
      'onlyself',
    ],
    variants: [
      'create',
      'read',
      'update',
      'delete',
      'list',
      'request',
      'approve',
      'manage',
      'access',
      'register',
      'modify',
      'remove',
      'import',
      'admin',
      'export',
      'print',
      'onlyself',
    ],
    items: [
      'create',
      'read',
      'update',
      'delete',
      'list',
      'request',
      'approve',
      'entry',
      'exit',
      'transfer',
      'manage',
      'access',
      'admin',
    ],
    movements: ['create', 'read', 'list', 'approve'],
    suppliers: [
      'create',
      'read',
      'update',
      'delete',
      'list',
      'manage',
      'access',
      'register',
      'modify',
      'remove',
    ],
    manufacturers: [
      'create',
      'read',
      'update',
      'delete',
      'list',
      'manage',
      'access',
      'register',
      'modify',
      'remove',
    ],
    locations: ['create', 'read', 'update', 'delete', 'list', 'manage'],
    categories: [
      'create',
      'read',
      'update',
      'delete',
      'list',
      'manage',
      'access',
      'register',
      'modify',
      'remove',
    ],
    tags: ['create', 'read', 'update', 'delete', 'list', 'manage'],
    templates: [
      'create',
      'read',
      'update',
      'delete',
      'list',
      'manage',
      'access',
      'register',
      'modify',
      'remove',
    ],
    'purchase-orders': [
      'create',
      'read',
      'update',
      'delete',
      'list',
      'approve',
      'cancel',
      'manage',
      'access',
      'register',
      'admin',
    ],
    care: ['list', 'read', 'set'],
    'product-attachments': ['create', 'read', 'delete'],
    'product-care-instructions': ['create', 'read', 'delete'],
    'variant-attachments': ['create', 'read', 'delete'],
    bins: ['list', 'read', 'update', 'manage', 'search'],
    inventory: ['access', 'register', 'modify', 'admin'],
    warehouses: [
      'create',
      'read',
      'update',
      'delete',
      'list',
      'manage',
      'access',
      'register',
      'modify',
      'remove',
      'admin',
    ],
    zones: [
      'create',
      'read',
      'update',
      'delete',
      'list',
      'manage',
      'configure',
      'access',
      'register',
      'modify',
      'remove',
    ],
    volumes: [
      'create',
      'read',
      'update',
      'delete',
      'list',
      'manage',
      'close',
      'reopen',
      'deliver',
      'return',
      'add-item',
      'remove-item',
      'romaneio',
      'access',
      'register',
      'modify',
      'remove',
      'admin',
      'print',
    ],
  },
  // SALES module
  sales: {
    customers: [
      'create',
      'read',
      'update',
      'delete',
      'list',
      'manage',
      'access',
      'register',
      'modify',
      'remove',
      'import',
      'export',
      'onlyself',
      'admin',
    ],
    contacts: ['access', 'register', 'modify', 'remove', 'admin', 'onlyself'],
    pipelines: ['access', 'admin'],
    deals: [
      'access',
      'register',
      'modify',
      'remove',
      'reassign',
      'admin',
      'onlyself',
    ],
    activities: ['access', 'register'],
    orders: [
      'create',
      'read',
      'update',
      'delete',
      'list',
      'request',
      'approve',
      'manage',
      'access',
      'register',
      'modify',
      'remove',
      'export',
      'print',
      'admin',
      'onlyself',
      'confirm',
      'cancel',
    ],
    promotions: ['create', 'read', 'update', 'delete', 'list', 'manage'],
    reservations: ['create', 'read', 'update', 'delete', 'list', 'manage'],
    comments: ['create', 'read', 'update', 'delete', 'list', 'manage'],
    notifications: ['create', 'read', 'update', 'delete', 'list'],
  },
  // RBAC module
  rbac: {
    permissions: ['create', 'read', 'update', 'delete', 'list', 'manage'],
    groups: ['create', 'read', 'update', 'delete', 'list', 'assign', 'manage'],
    audit: ['read', 'list'],
    assignments: ['create', 'read', 'update', 'delete', 'list', 'manage'],
    associations: ['create', 'read', 'update', 'delete', 'list', 'manage'],
    'user-groups': ['create', 'read', 'update', 'delete', 'list', 'manage'],
    'user-permissions': [
      'create',
      'read',
      'update',
      'delete',
      'list',
      'manage',
    ],
  },
  // REQUESTS module
  requests: {
    requests: [
      'create',
      'read',
      'update',
      'delete',
      'list',
      'assign',
      'approve',
      'reject',
      'cancel',
      'complete',
    ],
    comments: ['create', 'read', 'update', 'delete', 'list'],
    attachments: ['create', 'read', 'delete', 'list'],
  },
  // HR module
  hr: {
    companies: [
      'create',
      'read',
      'update',
      'delete',
      'list',
      'get_by_cnpj',
      'restore',
      'manage',
    ],
    employees: [
      'create',
      'read',
      'read.all',
      'read.team',
      'update',
      'update.all',
      'update.team',
      'delete',
      'list',
      'list.all',
      'list.team',
      'terminate',
      'manage',
      'access',
      'register',
      'modify',
      'remove',
      'import',
      'export',
      'print',
      'admin',
      'onlyself',
    ],
    departments: [
      'create',
      'read',
      'update',
      'delete',
      'list',
      'manage',
      'access',
      'register',
      'modify',
      'remove',
      'import',
    ],
    positions: [
      'create',
      'read',
      'update',
      'delete',
      'list',
      'manage',
      'access',
      'register',
      'modify',
      'remove',
      'import',
    ],
    absences: [
      'create',
      'read',
      'update',
      'delete',
      'list',
      'approve',
      'reject',
      'manage',
      'access',
      'register',
      'modify',
      'remove',
      'admin',
      'onlyself',
    ],
    vacations: [
      'create',
      'read',
      'update',
      'delete',
      'list',
      'approve',
      'reject',
      'manage',
      'access',
      'register',
      'modify',
      'admin',
      'onlyself',
    ],
    'time-entries': ['create', 'read', 'list', 'update', 'delete', 'manage'],
    overtime: [
      'create',
      'read',
      'read.all',
      'read.team',
      'update',
      'delete',
      'list',
      'list.all',
      'list.team',
      'approve',
      'approve.all',
      'approve.team',
      'reject',
      'manage',
    ],
    payroll: [
      'create',
      'read',
      'update',
      'delete',
      'list',
      'process',
      'approve',
      'pay',
      'access',
      'register',
      'export',
      'print',
      'admin',
    ],
    bonuses: [
      'create',
      'read',
      'update',
      'delete',
      'list',
      'access',
      'register',
      'modify',
      'remove',
    ],
    deductions: [
      'create',
      'read',
      'update',
      'delete',
      'list',
      'access',
      'register',
      'modify',
      'remove',
    ],
    'fiscal-settings': [
      'create',
      'read',
      'read_sensitive',
      'update',
      'delete',
      'list',
    ],
    stakeholders: [
      'create',
      'read',
      'read_sensitive',
      'update',
      'delete',
      'list',
      'sync_from_cnpj_api',
    ],
    'work-schedules': [
      'create',
      'read',
      'update',
      'delete',
      'list',
      'manage',
      'access',
      'register',
      'modify',
      'remove',
    ],
    'time-bank': ['create', 'read', 'update', 'list', 'manage'],
    'vacation-periods': [
      'create',
      'read',
      'update',
      'delete',
      'list',
      'schedule',
      'cancel',
      'complete',
      'sell',
      'manage',
    ],
    addresses: ['create', 'read', 'update', 'delete', 'list'],
    cnaes: ['create', 'read', 'update', 'delete', 'list'],
    'company-addresses': [
      'create',
      'read',
      'update',
      'delete',
      'list',
      'manage',
    ],
    'company-cnaes': ['create', 'read', 'update', 'delete', 'list', 'manage'],
    'company-fiscal-settings': [
      'create',
      'read',
      'update',
      'delete',
      'list',
      'manage',
    ],
    'company-stakeholder': [
      'create',
      'read',
      'update',
      'delete',
      'list',
      'manage',
    ],
    manufacturers: ['create', 'read', 'update', 'delete', 'list', 'manage'],
    suppliers: ['create', 'read', 'update', 'delete', 'list', 'manage'],
    payrolls: [
      'create',
      'read',
      'update',
      'delete',
      'list',
      'process',
      'approve',
      'pay',
      'manage',
    ],
    'time-control': [
      'create',
      'read',
      'update',
      'delete',
      'list',
      'manage',
      'access',
      'register',
      'export',
      'print',
      'admin',
    ],
    admissions: ['access', 'register', 'modify', 'remove', 'admin'],
    shifts: ['access', 'register', 'modify', 'remove', 'admin'],
    'medical-exams': ['access', 'register', 'modify', 'remove'],
    safety: ['access', 'register', 'modify', 'remove', 'admin'],
    ppe: ['access', 'register', 'modify', 'remove', 'admin'],
    training: ['access', 'register', 'modify', 'remove', 'admin'],
    reviews: ['access', 'register', 'modify', 'remove', 'admin'],
    benefits: ['access', 'register', 'modify', 'remove', 'admin'],
    announcements: ['access', 'register', 'modify', 'remove'],
    'employee-requests': ['access', 'register', 'admin'],
    kudos: ['access', 'register'],
    delegations: ['access', 'register', 'remove'],
    onboarding: ['access', 'register', 'modify', 'remove', 'admin'],
    offboarding: ['access', 'register', 'modify', 'remove', 'admin'],
    reports: ['access', 'export'],
    recruitment: ['access', 'register', 'modify', 'remove', 'admin'],
    surveys: ['access', 'register', 'modify', 'remove'],
    okrs: ['access', 'register', 'modify', 'remove'],
    warnings: ['access', 'register', 'modify', 'remove', 'admin'],
  },
  // ADMIN module (tenant-scoped admin operations)
  admin: {
    companies: ['create', 'read', 'update', 'delete', 'restore'],
    'company-addresses': ['create', 'read', 'update', 'delete', 'manage'],
    'company-cnaes': ['create', 'read', 'update', 'delete', 'manage'],
    'company-fiscal-settings': ['create', 'read', 'update', 'delete', 'manage'],
    'company-stakeholder': ['create', 'read', 'update', 'delete', 'manage'],
    settings: ['access', 'admin'],
    audit: ['access', 'admin'],
    users: ['access', 'admin', 'register', 'modify', 'remove'],
  },
  // FINANCE module
  finance: {
    companies: ['read'],
    'cost-centers': ['create', 'read', 'update', 'delete', 'list', 'manage'],
    'bank-accounts': [
      'create',
      'read',
      'update',
      'delete',
      'list',
      'manage',
      'admin',
      'import',
    ],
    categories: ['create', 'read', 'update', 'delete', 'list', 'manage'],
    entries: [
      'create',
      'read',
      'update',
      'delete',
      'list',
      'pay',
      'cancel',
      'manage',
      'register',
      'import',
      'access',
      'admin',
    ],
    attachments: ['create', 'read', 'delete', 'list'],
    loans: ['create', 'read', 'update', 'delete', 'list', 'pay', 'manage'],
    consortia: ['create', 'read', 'update', 'delete', 'list', 'pay', 'manage'],
    recurring: ['create', 'read', 'update', 'delete', 'list', 'manage'],
    contracts: ['create', 'read', 'update', 'delete', 'list', 'manage'],
    dashboard: ['view'],
    export: ['generate'],
  },
  // AUDIT module
  audit: {
    logs: ['view', 'list'],
    history: ['view'],
    rollback: ['preview', 'execute'],
    compare: ['view'],
  },
  // STORAGE module
  storage: {
    interface: ['view'],
    'user-folders': [
      'list',
      'create',
      'read',
      'update',
      'delete',
      'download',
      'share-user',
      'share-group',
    ],
    'filter-folders': ['list', 'read', 'download', 'share-user', 'share-group'],
    'system-folders': ['list', 'read', 'download', 'share-user', 'share-group'],
    files: [
      'list',
      'create',
      'read',
      'update',
      'delete',
      'download',
      'share-user',
      'share-group',
    ],
    versions: ['read', 'create', 'restore'],
    stats: ['view'],
    security: ['manage'],
  },
  // NOTIFICATIONS module
  notifications: {
    _root: ['broadcast', 'manage', 'schedule', 'send'],
    notifications: ['create', 'read', 'update', 'delete', 'list', 'manage'],
    preferences: ['create', 'read', 'update', 'delete', 'list'],
  },
  // CALENDAR module
  calendar: {
    events: [
      'create',
      'read',
      'update',
      'delete',
      'list',
      'manage',
      'share-users',
      'share-teams',
      'export',
    ],
    participants: ['invite', 'respond', 'manage'],
    reminders: ['create', 'delete'],
  },
  // REPORTS module
  reports: {
    stock: [
      'view',
      'generate',
      'inventory',
      'movements',
      'low-stock',
      'valuation',
    ],
    sales: [
      'view',
      'generate',
      'daily',
      'monthly',
      'by-customer',
      'by-product',
      'by-seller',
      'commissions',
    ],
    hr: ['view', 'generate', 'headcount', 'turnover', 'absences'],
  },
  // TASKS module (legacy 3-level codes — kept for backward compat)
  tasks: {
    boards: ['create', 'read', 'update', 'delete', 'list', 'manage'],
    cards: ['create', 'read', 'update', 'delete', 'list', 'move', 'assign'],
    comments: ['create', 'read', 'update', 'delete'],
    attachments: ['upload', 'delete'],
    watchers: ['create', 'read', 'delete'],
  },
  // TOOLS module (4-level codes: tools.{group}.{resource}.{action})
  // Controllers use PermissionCodes.TOOLS.* which generate these codes
  tools: {
    // Email
    'email.accounts': [
      'access',
      'register',
      'modify',
      'remove',
      'admin',
      'share',
    ],
    'email.messages': ['access', 'register', 'modify', 'remove', 'onlyself'],
    // Tasks
    'tasks.boards': ['access', 'register', 'modify', 'remove', 'share'],
    'tasks.cards': [
      'access',
      'register',
      'modify',
      'remove',
      'admin',
      'share',
      'onlyself',
    ],
    'tasks.comments': ['access', 'register', 'modify', 'remove'],
    'tasks.attachments': ['access', 'register', 'remove'],
    'tasks.labels': ['access', 'register', 'modify', 'remove'],
    'tasks.checklists': ['access', 'register', 'modify', 'remove'],
    'tasks.customfields': ['access', 'register', 'modify', 'remove'],
    // Calendar
    calendar: [
      'access',
      'register',
      'modify',
      'remove',
      'export',
      'admin',
      'share',
      'onlyself',
    ],
    // Storage
    'storage.folders': [
      'access',
      'register',
      'modify',
      'remove',
      'admin',
      'share',
    ],
    'storage.files': [
      'access',
      'register',
      'modify',
      'remove',
      'admin',
      'share',
      'onlyself',
    ],
    // Signature
    'signature.envelopes': ['access', 'register', 'modify', 'remove', 'admin'],
    'signature.certificates': ['access', 'register', 'remove', 'admin'],
    'signature.templates': ['access', 'register', 'modify', 'remove'],
    // Messaging
    'messaging.accounts': ['access', 'register', 'modify', 'remove', 'admin'],
    'messaging.contacts': ['access'],
    'messaging.messages': ['access', 'register'],
    // AI
    'ai.chat': ['access'],
    'ai.insights': ['access'],
    'ai.config': ['access', 'modify'],
    'ai.favorites': ['access', 'register', 'remove'],
    'ai.actions': ['access'],
  },
  // PRODUCTION module
  production: {
    engineering: ['access', 'register', 'modify', 'remove', 'admin'],
    orders: ['access', 'register', 'modify', 'remove', 'export', 'print', 'admin'],
    shopfloor: ['access', 'register', 'modify', 'admin'],
    planning: ['access', 'register', 'modify', 'admin'],
    quality: ['access', 'register', 'modify', 'admin'],
    costing: ['access', 'admin'],
    analytics: ['access', 'export'],
  },
};

/**
 * Generate permission code from module, resource and action
 */
export function generatePermissionCode(
  module: string,
  resource: string,
  action: string,
): string {
  return `${module}.${resource}.${action}`;
}

/**
 * Generate human-readable name for permission
 */
export function generatePermissionName(
  module: string,
  resource: string,
  action: string,
): string {
  const actionNames: Record<string, string> = {
    create: 'Criar',
    read: 'Visualizar',
    read_sensitive: 'Visualizar Dados Sensíveis',
    update: 'Atualizar',
    delete: 'Excluir',
    list: 'Listar',
    manage: 'Gerenciar',
    approve: 'Aprovar',
    reject: 'Rejeitar',
    request: 'Solicitar',
    assign: 'Atribuir',
    cancel: 'Cancelar',
    complete: 'Completar',
    process: 'Processar',
    pay: 'Pagar',
    restore: 'Restaurar',
    get_by_cnpj: 'Buscar por CNPJ',
    sync_from_cnpj_api: 'Sincronizar da API CNPJ',
    view: 'Visualizar',
    execute: 'Executar',
    preview: 'Pré-visualizar',
    schedule: 'Agendar',
    sell: 'Vender',
    close: 'Fechar',
    reopen: 'Reabrir',
    deliver: 'Entregar',
    return: 'Retornar',
    'add-item': 'Adicionar Item',
    'remove-item': 'Remover Item',
    romaneio: 'Romaneio',
    duplicate: 'Duplicar',
    generate: 'Gerar',
    link: 'Vincular',
    unlink: 'Desvincular',
    download: 'Baixar',
    'share-user': 'Compartilhar com Usuário',
    'share-group': 'Compartilhar com Grupo',
    'share-users': 'Compartilhar com Usuários',
    'share-teams': 'Compartilhar com Equipes',
    invite: 'Convidar',
    respond: 'Responder',
    export: 'Exportar',
    move: 'Mover',
    upload: 'Enviar',
    import: 'Importar',
    register: 'Registrar',
    access: 'Acessar',
    admin: 'Administrar',
    onlyself: 'Apenas Próprio',
  };

  const resourceNames: Record<string, string> = {
    users: 'Usuários',
    sessions: 'Sessões',
    profiles: 'Perfis',
    'label-templates': 'Templates de Etiquetas',
    products: 'Produtos',
    variants: 'Variantes',
    items: 'Itens',
    movements: 'Movimentações',
    suppliers: 'Fornecedores',
    manufacturers: 'Fabricantes',
    locations: 'Localizações',
    categories: 'Categorias',
    tags: 'Tags',
    templates: 'Templates',
    'purchase-orders': 'Pedidos de Compra',
    'product-attachments': 'Anexos de Produto',
    'product-care-instructions': 'Instruções de Cuidado de Produto',
    'variant-attachments': 'Anexos de Variante',
    customers: 'Clientes',
    contacts: 'Contatos',
    pipelines: 'Pipelines',
    orders: 'Pedidos',
    promotions: 'Promoções',
    reservations: 'Reservas',
    comments: 'Comentários',
    permissions: 'Permissões',
    groups: 'Grupos',
    audit: 'Auditoria',
    requests: 'Solicitações',
    attachments: 'Anexos',
    companies: 'Empresas',
    employees: 'Funcionários',
    departments: 'Departamentos',
    positions: 'Cargos',
    absences: 'Ausências',
    vacations: 'Férias',
    'time-entries': 'Registros de Ponto',
    overtime: 'Horas Extras',
    payroll: 'Folha de Pagamento',
    bonuses: 'Bônus',
    deductions: 'Deduções',
    'fiscal-settings': 'Configurações Fiscais',
    stakeholders: 'Sócios',
    'work-schedules': 'Jornadas de Trabalho',
    'time-bank': 'Banco de Horas',
    'vacation-periods': 'Períodos de Férias',
    addresses: 'Endereços',
    cnaes: 'CNAEs',
    'company-addresses': 'Endereços da Empresa',
    'company-cnaes': 'CNAEs da Empresa',
    'company-fiscal-settings': 'Configurações Fiscais da Empresa',
    'company-stakeholder': 'Sócios da Empresa',
    payrolls: 'Folhas de Pagamento',
    'time-control': 'Controle de Ponto',
    shifts: 'Turnos',
    'medical-exams': 'Exames Médicos',
    safety: 'Segurança do Trabalho',
    ppe: 'EPIs',
    training: 'Treinamentos',
    reviews: 'Avaliações de Desempenho',
    benefits: 'Benefícios',
    announcements: 'Comunicados',
    'employee-requests': 'Solicitações de Funcionários',
    kudos: 'Reconhecimentos',
    delegations: 'Delegações',
    onboarding: 'Onboarding',
    offboarding: 'Offboarding',
    reports: 'Relatórios',
    recruitment: 'Recrutamento',
    surveys: 'Pesquisas',
    okrs: 'OKRs',
    warnings: 'Advertências',
    assignments: 'Atribuições',
    associations: 'Associações',
    'user-groups': 'Grupos de Usuários',
    'user-permissions': 'Permissões de Usuários',
    logs: 'Logs',
    history: 'Histórico',
    rollback: 'Rollback',
    compare: 'Comparação',
    notifications: 'Notificações',
    preferences: 'Preferências',
    volumes: 'Volumes',
    'cost-centers': 'Centros de Custo',
    'bank-accounts': 'Contas Bancárias',
    entries: 'Lançamentos Financeiros',
    loans: 'Empréstimos',
    consortia: 'Consórcios',
    dashboard: 'Dashboard Financeiro',
    export: 'Exportação Contábil',
    interface: 'Interface',
    'user-folders': 'Pastas de Usuário',
    'filter-folders': 'Pastas de Filtro',
    'system-folders': 'Pastas do Sistema',
    files: 'Arquivos',
    versions: 'Versões',
    stats: 'Estatísticas',
    events: 'Eventos',
    participants: 'Participantes',
    reminders: 'Lembretes',
    boards: 'Quadros',
    cards: 'Cartões',
  };

  const actionName = actionNames[action] || action;
  const resourceName = resourceNames[resource] || resource;

  return `${actionName} ${resourceName}`;
}

/**
 * Flatten ALL_PERMISSIONS into an array of { code, name, description, module, resource, action }
 */
export function flattenPermissions(): Array<{
  code: string;
  name: string;
  description: string;
  module: string;
  resource: string;
  action: string;
}> {
  const result: Array<{
    code: string;
    name: string;
    description: string;
    module: string;
    resource: string;
    action: string;
  }> = [];

  for (const [module, resources] of Object.entries(ALL_PERMISSIONS)) {
    for (const [resource, actions] of Object.entries(resources)) {
      for (const action of actions) {
        const code = generatePermissionCode(module, resource, action);
        const name = generatePermissionName(module, resource, action);
        result.push({
          code,
          name,
          description: `Permissão para ${name.toLowerCase()} no módulo ${module}`,
          module,
          resource,
          action,
        });
      }
    }
  }

  return result;
}

/** Slug used for the global admin group in E2E tests */
export const ADMIN_TEST_GROUP_SLUG = 'admin-test';
