/**
 * Machine-readable error codes for API responses.
 * Frontend can use these codes for i18n and conditional error handling.
 */
export const ErrorCodes = {
  // Generic
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // Auth
  USER_BLOCKED: 'USER_BLOCKED',
  PASSWORD_RESET_REQUIRED: 'PASSWORD_RESET_REQUIRED',
  PIN_SETUP_REQUIRED: 'PIN_SETUP_REQUIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',

  // Multi-tenant
  PLAN_LIMIT_EXCEEDED: 'PLAN_LIMIT_EXCEEDED',
  CROSS_TENANT: 'CROSS_TENANT',

  // Domain-specific
  VOLUME_NOT_FOUND: 'VOLUME_NOT_FOUND',
  VOLUME_ALREADY_EXISTS: 'VOLUME_ALREADY_EXISTS',
  VOLUME_CANNOT_BE_CLOSED: 'VOLUME_CANNOT_BE_CLOSED',
  VOLUME_ITEM_NOT_FOUND: 'VOLUME_ITEM_NOT_FOUND',
  VOLUME_ITEM_ALREADY_EXISTS: 'VOLUME_ITEM_ALREADY_EXISTS',
  INVALID_VOLUME_STATUS: 'INVALID_VOLUME_STATUS',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
