/**
 * Machine-readable error codes for API responses.
 * Frontend can use these codes for i18n and conditional error handling.
 */
export const ErrorCodes = {
  // Generic
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  CONFLICT: 'CONFLICT',
  OPTIMISTIC_LOCK_CONFLICT: 'OPTIMISTIC_LOCK_CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // Auth
  USER_BLOCKED: 'USER_BLOCKED',
  PASSWORD_RESET_REQUIRED: 'PASSWORD_RESET_REQUIRED',
  PIN_SETUP_REQUIRED: 'PIN_SETUP_REQUIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',

  // Multi-tenant
  PLAN_LIMIT_EXCEEDED: 'PLAN_LIMIT_EXCEEDED',
  CROSS_TENANT: 'CROSS_TENANT',

  // Finance
  FINANCE_CATEGORY_MAX_DEPTH: 'FINANCE_CATEGORY_MAX_DEPTH',
  FINANCE_CATEGORY_REPLACEMENT_REQUIRED:
    'FINANCE_CATEGORY_REPLACEMENT_REQUIRED',
  FINANCE_CATEGORY_REPLACEMENT_NOT_FOUND:
    'FINANCE_CATEGORY_REPLACEMENT_NOT_FOUND',
  FINANCE_CATEGORY_SELF_REPLACEMENT: 'FINANCE_CATEGORY_SELF_REPLACEMENT',
  FINANCE_CATEGORY_IS_SYSTEM: 'FINANCE_CATEGORY_IS_SYSTEM',
  FINANCE_CATEGORY_HAS_CHILDREN: 'FINANCE_CATEGORY_HAS_CHILDREN',
  FINANCE_CATEGORY_NOT_FOUND: 'FINANCE_CATEGORY_NOT_FOUND',
  FINANCE_CATEGORY_DUPLICATE_SLUG: 'FINANCE_CATEGORY_DUPLICATE_SLUG',
  FINANCE_BANK_ACCOUNT_NOT_FOUND: 'FINANCE_BANK_ACCOUNT_NOT_FOUND',
  FINANCE_COST_CENTER_NOT_FOUND: 'FINANCE_COST_CENTER_NOT_FOUND',
  FINANCE_RATEIO_INVALID_PERCENTAGE: 'FINANCE_RATEIO_INVALID_PERCENTAGE',
  FINANCE_RATEIO_CONFLICT: 'FINANCE_RATEIO_CONFLICT',
  FINANCE_CANNOT_DELETE_PAID_ENTRY: 'FINANCE_CANNOT_DELETE_PAID_ENTRY',

  // Domain-specific
  VOLUME_NOT_FOUND: 'VOLUME_NOT_FOUND',
  VOLUME_ALREADY_EXISTS: 'VOLUME_ALREADY_EXISTS',
  VOLUME_CANNOT_BE_CLOSED: 'VOLUME_CANNOT_BE_CLOSED',
  VOLUME_ITEM_NOT_FOUND: 'VOLUME_ITEM_NOT_FOUND',
  VOLUME_ITEM_ALREADY_EXISTS: 'VOLUME_ITEM_ALREADY_EXISTS',
  INVALID_VOLUME_STATUS: 'INVALID_VOLUME_STATUS',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
