import { z } from 'zod';

export const createFinanceEntrySchema = z.object({
  type: z.enum(['PAYABLE', 'RECEIVABLE']),
  description: z.string().min(1).max(500),
  notes: z.string().optional(),
  categoryId: z.string().uuid(),
  costCenterId: z.string().uuid(),
  bankAccountId: z.string().uuid().optional(),
  supplierName: z.string().max(256).optional(),
  customerName: z.string().max(256).optional(),
  supplierId: z.string().uuid().optional(),
  customerId: z.string().uuid().optional(),
  salesOrderId: z.string().uuid().optional(),
  expectedAmount: z.number().positive(),
  discount: z.number().min(0).optional(),
  interest: z.number().min(0).optional(),
  penalty: z.number().min(0).optional(),
  issueDate: z.coerce.date(),
  dueDate: z.coerce.date(),
  competenceDate: z.coerce.date().optional(),
  recurrenceType: z.enum(['SINGLE', 'RECURRING', 'INSTALLMENT']).optional(),
  recurrenceInterval: z.number().int().positive().optional(),
  recurrenceUnit: z
    .enum([
      'DAILY',
      'WEEKLY',
      'BIWEEKLY',
      'MONTHLY',
      'QUARTERLY',
      'SEMIANNUAL',
      'ANNUAL',
    ])
    .optional(),
  totalInstallments: z.number().int().positive().optional(),
  currentInstallment: z.number().int().positive().optional(),
  boletoBarcode: z.string().max(64).optional(),
  boletoDigitLine: z.string().max(64).optional(),
  tags: z.array(z.string()).optional(),
});

export const updateFinanceEntrySchema = z.object({
  description: z.string().min(1).max(500).optional(),
  notes: z.string().nullable().optional(),
  categoryId: z.string().uuid().optional(),
  costCenterId: z.string().uuid().optional(),
  bankAccountId: z.string().uuid().nullable().optional(),
  supplierName: z.string().max(256).nullable().optional(),
  customerName: z.string().max(256).nullable().optional(),
  expectedAmount: z.number().positive().optional(),
  discount: z.number().min(0).optional(),
  interest: z.number().min(0).optional(),
  penalty: z.number().min(0).optional(),
  dueDate: z.coerce.date().optional(),
  competenceDate: z.coerce.date().nullable().optional(),
  boletoBarcode: z.string().max(64).nullable().optional(),
  boletoDigitLine: z.string().max(64).nullable().optional(),
  tags: z.array(z.string()).optional(),
});

export const financeEntryResponseSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string().uuid(),
  type: z.string(),
  code: z.string(),
  description: z.string(),
  notes: z.string().optional().nullable(),
  categoryId: z.string().uuid(),
  costCenterId: z.string().uuid(),
  bankAccountId: z.string().uuid().optional().nullable(),
  supplierName: z.string().optional().nullable(),
  customerName: z.string().optional().nullable(),
  supplierId: z.string().optional().nullable(),
  customerId: z.string().optional().nullable(),
  salesOrderId: z.string().optional().nullable(),
  expectedAmount: z.number(),
  actualAmount: z.number().optional().nullable(),
  discount: z.number(),
  interest: z.number(),
  penalty: z.number(),
  totalDue: z.number(),
  remainingBalance: z.number(),
  isOverdue: z.boolean(),
  issueDate: z.coerce.date(),
  dueDate: z.coerce.date(),
  competenceDate: z.coerce.date().optional().nullable(),
  paymentDate: z.coerce.date().optional().nullable(),
  status: z.string(),
  recurrenceType: z.string(),
  recurrenceInterval: z.number().optional().nullable(),
  recurrenceUnit: z.string().optional().nullable(),
  totalInstallments: z.number().optional().nullable(),
  currentInstallment: z.number().optional().nullable(),
  parentEntryId: z.string().uuid().optional().nullable(),
  boletoBarcode: z.string().optional().nullable(),
  boletoDigitLine: z.string().optional().nullable(),
  tags: z.array(z.string()),
  createdBy: z.string().optional().nullable(),
  createdAt: z.coerce.date(),
  updatedAt: z.coerce.date().optional().nullable(),
  deletedAt: z.coerce.date().optional().nullable(),
});

export const parseBoletoSchema = z.object({
  barcode: z.string().min(44).max(54),
});

export const parseBoletoResponseSchema = z.object({
  bankCode: z.string(),
  bankName: z.string(),
  amount: z.number(),
  dueDate: z.coerce.date(),
  barcode: z.string(),
  digitLine: z.string(),
});

export const listFinanceEntriesQuerySchema = z.object({
  page: z.coerce.number().int().positive().optional().default(1),
  limit: z.coerce.number().int().positive().max(100).optional().default(20),
  type: z.enum(['PAYABLE', 'RECEIVABLE']).optional(),
  status: z
    .enum([
      'PENDING',
      'OVERDUE',
      'PAID',
      'RECEIVED',
      'PARTIALLY_PAID',
      'CANCELLED',
      'SCHEDULED',
    ])
    .optional(),
  categoryId: z.string().uuid().optional(),
  costCenterId: z.string().uuid().optional(),
  bankAccountId: z.string().uuid().optional(),
  dueDateFrom: z.coerce.date().optional(),
  dueDateTo: z.coerce.date().optional(),
  isOverdue: z
    .enum(['true', 'false'])
    .transform((v) => v === 'true')
    .optional(),
  customerName: z.string().optional(),
  supplierName: z.string().optional(),
  overdueRange: z.enum(['1-7', '8-30', '31-60', '60+']).optional(),
  search: z.string().optional(),
});
