export enum AuditAction {
  // CRUD básico
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  RESTORE = 'RESTORE',

  // Autenticação e Sessão
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  SESSION_REFRESH = 'SESSION_REFRESH',
  SESSION_EXPIRE = 'SESSION_EXPIRE',
  SESSION_REVOKE = 'SESSION_REVOKE',

  // Senha e Segurança
  PASSWORD_CHANGE = 'PASSWORD_CHANGE',
  PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST',
  PASSWORD_RESET_COMPLETE = 'PASSWORD_RESET_COMPLETE',
  PASSWORD_FORCE_RESET = 'PASSWORD_FORCE_RESET',
  PIN_CHANGE = 'PIN_CHANGE',
  PIN_FORCE_RESET = 'PIN_FORCE_RESET',

  // Perfil de Usuário
  EMAIL_CHANGE = 'EMAIL_CHANGE',
  USERNAME_CHANGE = 'USERNAME_CHANGE',
  PROFILE_CHANGE = 'PROFILE_CHANGE',

  // RBAC - Permissões
  PERMISSION_GRANT = 'PERMISSION_GRANT',
  PERMISSION_REVOKE = 'PERMISSION_REVOKE',
  PERMISSION_UPDATE = 'PERMISSION_UPDATE',
  GROUP_ASSIGN = 'GROUP_ASSIGN',
  GROUP_REMOVE = 'GROUP_REMOVE',
  PERMISSION_ADD_TO_GROUP = 'PERMISSION_ADD_TO_GROUP',
  PERMISSION_REMOVE_FROM_GROUP = 'PERMISSION_REMOVE_FROM_GROUP',

  // Estoque
  PRICE_CHANGE = 'PRICE_CHANGE',
  STOCK_ENTRY = 'STOCK_ENTRY',
  STOCK_EXIT = 'STOCK_EXIT',
  STOCK_TRANSFER = 'STOCK_TRANSFER',
  STOCK_ADJUSTMENT = 'STOCK_ADJUSTMENT',

  // Pedidos e Compras
  ORDER_CREATE = 'ORDER_CREATE',
  ORDER_CANCEL = 'ORDER_CANCEL',
  STATUS_CHANGE = 'STATUS_CHANGE',

  // Reservas
  RESERVATION_CREATE = 'RESERVATION_CREATE',
  RESERVATION_RELEASE = 'RESERVATION_RELEASE',

  // HR - Funcionários
  EMPLOYEE_HIRE = 'EMPLOYEE_HIRE',
  EMPLOYEE_TERMINATE = 'EMPLOYEE_TERMINATE',
  EMPLOYEE_TRANSFER = 'EMPLOYEE_TRANSFER',
  EMPLOYEE_LINK_USER = 'EMPLOYEE_LINK_USER',

  // HR - Ponto e Tempo
  CLOCK_IN = 'CLOCK_IN',
  CLOCK_OUT = 'CLOCK_OUT',
  TIME_CALCULATE = 'TIME_CALCULATE',
  TIME_BANK_CREDIT = 'TIME_BANK_CREDIT',
  TIME_BANK_DEBIT = 'TIME_BANK_DEBIT',
  TIME_BANK_ADJUST = 'TIME_BANK_ADJUST',

  // HR - Ausências e Férias
  ABSENCE_REQUEST = 'ABSENCE_REQUEST',
  ABSENCE_APPROVE = 'ABSENCE_APPROVE',
  ABSENCE_REJECT = 'ABSENCE_REJECT',
  ABSENCE_CANCEL = 'ABSENCE_CANCEL',
  VACATION_SCHEDULE = 'VACATION_SCHEDULE',
  VACATION_START = 'VACATION_START',
  VACATION_COMPLETE = 'VACATION_COMPLETE',
  VACATION_CANCEL = 'VACATION_CANCEL',
  VACATION_SELL = 'VACATION_SELL',

  // HR - Horas Extras
  OVERTIME_REQUEST = 'OVERTIME_REQUEST',
  OVERTIME_APPROVE = 'OVERTIME_APPROVE',

  // Payroll - Folha de Pagamento
  PAYROLL_CREATE = 'PAYROLL_CREATE',
  PAYROLL_CALCULATE = 'PAYROLL_CALCULATE',
  PAYROLL_APPROVE = 'PAYROLL_APPROVE',
  PAYROLL_CANCEL = 'PAYROLL_CANCEL',
  PAYROLL_PAY = 'PAYROLL_PAY',

  // Requests - Workflow
  REQUEST_CREATE = 'REQUEST_CREATE',
  REQUEST_ASSIGN = 'REQUEST_ASSIGN',
  REQUEST_COMPLETE = 'REQUEST_COMPLETE',
  REQUEST_CANCEL = 'REQUEST_CANCEL',
  REQUEST_COMMENT = 'REQUEST_COMMENT',
  REQUEST_INFO = 'REQUEST_INFO',
  REQUEST_INFO_PROVIDE = 'REQUEST_INFO_PROVIDE',

  // Notificações
  NOTIFICATION_SEND = 'NOTIFICATION_SEND',
  NOTIFICATION_READ = 'NOTIFICATION_READ',
  NOTIFICATION_DELETE = 'NOTIFICATION_DELETE',

  // Verificações
  CHECK_CPF = 'CHECK_CPF',
  CHECK_CNPJ = 'CHECK_CNPJ',

  // Finance - Pagamentos
  PAYMENT_REGISTER = 'PAYMENT_REGISTER',
  PAYMENT_CANCEL = 'PAYMENT_CANCEL',
  ENTRY_CANCEL = 'ENTRY_CANCEL',
  CONTEMPLATION = 'CONTEMPLATION',

  // Sistema
  EXPORT = 'EXPORT',
  IMPORT = 'IMPORT',
  SYNC = 'SYNC',
  DUPLICATE = 'DUPLICATE',
  GENERATE = 'GENERATE',
  OTHER = 'OTHER',
}
