export enum AuditModule {
  CORE = 'CORE',
  AUTH = 'AUTH',
  RBAC = 'RBAC',
  STOCK = 'STOCK',
  SALES = 'SALES',
  HR = 'HR',
  PAYROLL = 'PAYROLL',
  REQUESTS = 'REQUESTS',
  NOTIFICATIONS = 'NOTIFICATIONS',
  FINANCE = 'FINANCE',
  SYSTEM = 'SYSTEM',
  OTHER = 'OTHER',
}
