export enum AuditAction {
  // CRUD básico
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  RESTORE = 'RESTORE',

  // Autenticação e Sessão
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  SESSION_REFRESH = 'SESSION_REFRESH',
  SESSION_EXPIRE = 'SESSION_EXPIRE',
  SESSION_REVOKE = 'SESSION_REVOKE',

  // Senha e Segurança
  PASSWORD_CHANGE = 'PASSWORD_CHANGE',
  PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST',
  PASSWORD_RESET_COMPLETE = 'PASSWORD_RESET_COMPLETE',
  PASSWORD_FORCE_RESET = 'PASSWORD_FORCE_RESET',
  PIN_CHANGE = 'PIN_CHANGE',
  PIN_FORCE_RESET = 'PIN_FORCE_RESET',

  // Perfil de Usuário
  EMAIL_CHANGE = 'EMAIL_CHANGE',
  USERNAME_CHANGE = 'USERNAME_CHANGE',
  PROFILE_CHANGE = 'PROFILE_CHANGE',

  // RBAC - Permissões
  PERMISSION_GRANT = 'PERMISSION_GRANT',
  PERMISSION_REVOKE = 'PERMISSION_REVOKE',
  PERMISSION_UPDATE = 'PERMISSION_UPDATE',
  GROUP_ASSIGN = 'GROUP_ASSIGN',
  GROUP_REMOVE = 'GROUP_REMOVE',
  PERMISSION_ADD_TO_GROUP = 'PERMISSION_ADD_TO_GROUP',
  PERMISSION_REMOVE_FROM_GROUP = 'PERMISSION_REMOVE_FROM_GROUP',

  // Estoque
  PRICE_CHANGE = 'PRICE_CHANGE',
  STOCK_ENTRY = 'STOCK_ENTRY',
  STOCK_EXIT = 'STOCK_EXIT',
  STOCK_TRANSFER = 'STOCK_TRANSFER',
  STOCK_ADJUSTMENT = 'STOCK_ADJUSTMENT',

  // Pedidos e Compras
  ORDER_CREATE = 'ORDER_CREATE',
  ORDER_CANCEL = 'ORDER_CANCEL',
  ORDER_CONFIRM = 'ORDER_CONFIRM',
  ORDER_STAGE_CHANGE = 'ORDER_STAGE_CHANGE',
  ORDER_CONVERT_QUOTE = 'ORDER_CONVERT_QUOTE',
  RETURN_CREATE = 'RETURN_CREATE',
  RETURN_APPROVE = 'RETURN_APPROVE',
  STATUS_CHANGE = 'STATUS_CHANGE',

  // Reservas
  RESERVATION_CREATE = 'RESERVATION_CREATE',
  RESERVATION_RELEASE = 'RESERVATION_RELEASE',

  // CRM
  STAGE_CHANGE_DEAL = 'STAGE_CHANGE_DEAL',

  // HR - Funcionários
  EMPLOYEE_HIRE = 'EMPLOYEE_HIRE',
  EMPLOYEE_TERMINATE = 'EMPLOYEE_TERMINATE',
  EMPLOYEE_TRANSFER = 'EMPLOYEE_TRANSFER',
  EMPLOYEE_LINK_USER = 'EMPLOYEE_LINK_USER',
  EMPLOYEE_UNLINK_USER = 'EMPLOYEE_UNLINK_USER',
  EMPLOYEE_SUSPEND = 'EMPLOYEE_SUSPEND',
  EMPLOYEE_REACTIVATE = 'EMPLOYEE_REACTIVATE',
  EMPLOYEE_ON_LEAVE = 'EMPLOYEE_ON_LEAVE',
  EMPLOYEE_ANONYMIZED = 'EMPLOYEE_ANONYMIZED',
  EMPLOYEE_REGENERATE_SHORT_ID = 'EMPLOYEE_REGENERATE_SHORT_ID',

  // HR - Ponto e Tempo
  CLOCK_IN = 'CLOCK_IN',
  CLOCK_OUT = 'CLOCK_OUT',
  TIME_CALCULATE = 'TIME_CALCULATE',
  TIME_BANK_CREDIT = 'TIME_BANK_CREDIT',
  TIME_BANK_DEBIT = 'TIME_BANK_DEBIT',
  TIME_BANK_ADJUST = 'TIME_BANK_ADJUST',

  // HR - Advertências (Warnings)
  WARNING_CREATE = 'WARNING_CREATE',
  WARNING_UPDATE = 'WARNING_UPDATE',
  WARNING_DELETE = 'WARNING_DELETE',
  WARNING_REVOKE = 'WARNING_REVOKE',
  WARNING_ACKNOWLEDGE = 'WARNING_ACKNOWLEDGE',

  // HR - Histórico Salarial
  SALARY_CHANGE = 'SALARY_CHANGE',

  // HR - 1:1 Meetings
  ONE_ON_ONE_SCHEDULE = 'ONE_ON_ONE_SCHEDULE',
  ONE_ON_ONE_UPDATE = 'ONE_ON_ONE_UPDATE',
  ONE_ON_ONE_CANCEL = 'ONE_ON_ONE_CANCEL',
  ONE_ON_ONE_COMPLETE = 'ONE_ON_ONE_COMPLETE',
  ONE_ON_ONE_DELETE = 'ONE_ON_ONE_DELETE',
  TALKING_POINT_ADD = 'TALKING_POINT_ADD',
  TALKING_POINT_UPDATE = 'TALKING_POINT_UPDATE',
  TALKING_POINT_DELETE = 'TALKING_POINT_DELETE',
  ACTION_ITEM_ADD = 'ACTION_ITEM_ADD',
  ACTION_ITEM_UPDATE = 'ACTION_ITEM_UPDATE',
  ACTION_ITEM_DELETE = 'ACTION_ITEM_DELETE',

  // HR - Ausências e Férias
  ABSENCE_REQUEST = 'ABSENCE_REQUEST',
  ABSENCE_APPROVE = 'ABSENCE_APPROVE',
  ABSENCE_REJECT = 'ABSENCE_REJECT',
  ABSENCE_CANCEL = 'ABSENCE_CANCEL',
  VACATION_SCHEDULE = 'VACATION_SCHEDULE',
  VACATION_START = 'VACATION_START',
  VACATION_COMPLETE = 'VACATION_COMPLETE',
  VACATION_CANCEL = 'VACATION_CANCEL',
  VACATION_SELL = 'VACATION_SELL',

  // HR - Horas Extras
  OVERTIME_REQUEST = 'OVERTIME_REQUEST',
  OVERTIME_APPROVE = 'OVERTIME_APPROVE',
  OVERTIME_REJECT = 'OVERTIME_REJECT',

  // Payroll - Folha de Pagamento
  PAYROLL_CREATE = 'PAYROLL_CREATE',
  PAYROLL_CALCULATE = 'PAYROLL_CALCULATE',
  PAYROLL_APPROVE = 'PAYROLL_APPROVE',
  PAYROLL_CANCEL = 'PAYROLL_CANCEL',
  PAYROLL_PAY = 'PAYROLL_PAY',

  // HR - Benefícios
  BENEFIT_ENROLL = 'BENEFIT_ENROLL',
  BENEFIT_CANCEL = 'BENEFIT_CANCEL',
  BENEFIT_BULK_ENROLL = 'BENEFIT_BULK_ENROLL',
  FLEX_BENEFIT_ALLOCATE = 'FLEX_BENEFIT_ALLOCATE',
  BENEFIT_DEDUCTION_CALCULATE = 'BENEFIT_DEDUCTION_CALCULATE',

  // HR - Rescisões
  TERMINATION_CREATE = 'TERMINATION_CREATE',
  TERMINATION_CALCULATE = 'TERMINATION_CALCULATE',
  TERMINATION_PAY = 'TERMINATION_PAY',

  // Requests - Workflow
  REQUEST_CREATE = 'REQUEST_CREATE',
  REQUEST_ASSIGN = 'REQUEST_ASSIGN',
  REQUEST_COMPLETE = 'REQUEST_COMPLETE',
  REQUEST_CANCEL = 'REQUEST_CANCEL',
  REQUEST_COMMENT = 'REQUEST_COMMENT',
  REQUEST_INFO = 'REQUEST_INFO',
  REQUEST_INFO_PROVIDE = 'REQUEST_INFO_PROVIDE',

  // Notificações
  NOTIFICATION_SEND = 'NOTIFICATION_SEND',
  NOTIFICATION_READ = 'NOTIFICATION_READ',
  NOTIFICATION_DELETE = 'NOTIFICATION_DELETE',

  // Verificações
  CHECK_CPF = 'CHECK_CPF',
  CHECK_CNPJ = 'CHECK_CNPJ',

  // Storage - Arquivos
  FILE_UPLOAD = 'FILE_UPLOAD',
  FILE_DOWNLOAD = 'FILE_DOWNLOAD',
  FILE_ACCESS = 'FILE_ACCESS',
  FILE_MOVE = 'FILE_MOVE',
  FILE_RENAME = 'FILE_RENAME',
  FILE_VERSION_UPLOAD = 'FILE_VERSION_UPLOAD',
  FILE_VERSION_RESTORE = 'FILE_VERSION_RESTORE',
  FOLDER_MOVE = 'FOLDER_MOVE',
  FOLDER_RENAME = 'FOLDER_RENAME',
  ACCESS_GRANT = 'ACCESS_GRANT',
  ACCESS_REVOKE = 'ACCESS_REVOKE',
  BULK_MOVE = 'BULK_MOVE',
  BULK_DELETE = 'BULK_DELETE',
  ITEM_PROTECT = 'ITEM_PROTECT',
  ITEM_UNPROTECT = 'ITEM_UNPROTECT',
  ITEM_HIDE = 'ITEM_HIDE',
  ITEM_UNHIDE = 'ITEM_UNHIDE',
  FILE_COMPRESS = 'FILE_COMPRESS',
  FILE_DECOMPRESS = 'FILE_DECOMPRESS',

  // Finance - Pagamentos
  RECONCILIATION_IMPORT = 'RECONCILIATION_IMPORT',
  RECONCILIATION_MATCH = 'RECONCILIATION_MATCH',
  RECONCILIATION_IGNORE = 'RECONCILIATION_IGNORE',
  RECONCILIATION_COMPLETE = 'RECONCILIATION_COMPLETE',
  RECONCILIATION_CANCEL = 'RECONCILIATION_CANCEL',
  RECONCILIATION_SUGGESTION_ACCEPT = 'RECONCILIATION_SUGGESTION_ACCEPT',
  RECONCILIATION_SUGGESTION_REJECT = 'RECONCILIATION_SUGGESTION_REJECT',
  PAYMENT_REGISTER = 'PAYMENT_REGISTER',
  PAYMENT_CANCEL = 'PAYMENT_CANCEL',
  ENTRY_CANCEL = 'ENTRY_CANCEL',
  RETENTION_APPLY = 'RETENTION_APPLY',
  CONTEMPLATION = 'CONTEMPLATION',

  // Teams
  MEMBER_ADD = 'MEMBER_ADD',
  MEMBER_REMOVE = 'MEMBER_REMOVE',
  ROLE_CHANGE = 'ROLE_CHANGE',
  OWNERSHIP_TRANSFER = 'OWNERSHIP_TRANSFER',

  // Email
  EMAIL_SEND = 'EMAIL_SEND',
  EMAIL_SHARE = 'EMAIL_SHARE',
  EMAIL_UNSHARE = 'EMAIL_UNSHARE',
  EMAIL_ATTACHMENT_DOWNLOAD = 'EMAIL_ATTACHMENT_DOWNLOAD',
  EMAIL_SYNC = 'EMAIL_SYNC',

  // Admin - Gestão de Tenants
  PLAN_CHANGE = 'PLAN_CHANGE',
  FLAG_CHANGE = 'FLAG_CHANGE',
  SECURITY_KEY_CHANGE = 'SECURITY_KEY_CHANGE',

  // Conversations
  CONVERSATION_CLOSE = 'CONVERSATION_CLOSE',
  CONVERSATION_ARCHIVE = 'CONVERSATION_ARCHIVE',
  MESSAGE_SEND = 'MESSAGE_SEND',

  // Forms
  FORM_PUBLISH = 'FORM_PUBLISH',
  FORM_UNPUBLISH = 'FORM_UNPUBLISH',
  FORM_SUBMIT = 'FORM_SUBMIT',

  // POS - Operador
  POS_OPERATOR_ASSIGN = 'POS_OPERATOR_ASSIGN',
  POS_OPERATOR_REVOKE = 'POS_OPERATOR_REVOKE',

  // POS - Configuração de Terminal (Emporion Plan A — Task 25)
  POS_TERMINAL_SESSION_MODE_UPDATE = 'POS_TERMINAL_SESSION_MODE_UPDATE',
  POS_TERMINAL_ZONE_ASSIGN = 'POS_TERMINAL_ZONE_ASSIGN',
  POS_TERMINAL_ZONE_UNASSIGN = 'POS_TERMINAL_ZONE_UNASSIGN',

  // POS - Vendas (Emporion Plan A — Task 28)
  POS_SALE_CREATE = 'POS_SALE_CREATE',
  POS_SALE_CONFLICT = 'POS_SALE_CONFLICT',

  // POS - Resolução manual de conflito (Emporion Plan A — Task 31)
  POS_CONFLICT_RESOLVE_CANCEL_AND_REFUND = 'POS_CONFLICT_RESOLVE_CANCEL_AND_REFUND',
  POS_CONFLICT_RESOLVE_FORCE_ADJUSTMENT = 'POS_CONFLICT_RESOLVE_FORCE_ADJUSTMENT',
  POS_CONFLICT_RESOLVE_SUBSTITUTE_ITEM = 'POS_CONFLICT_RESOLVE_SUBSTITUTE_ITEM',

  // POS - Configuração e emissão fiscal (Emporion Plan A — Task 32)
  POS_FISCAL_CONFIG_UPDATE = 'POS_FISCAL_CONFIG_UPDATE',
  POS_FISCAL_EMIT = 'POS_FISCAL_EMIT',

  // Cashier
  CASHIER_OPEN = 'CASHIER_OPEN',
  CASHIER_CLOSE = 'CASHIER_CLOSE',
  CASHIER_RECONCILE = 'CASHIER_RECONCILE',
  CASH_MOVEMENT = 'CASH_MOVEMENT',

  // Portal do Colaborador
  KUDOS_SEND = 'KUDOS_SEND',
  KUDOS_REACT = 'KUDOS_REACT',
  KUDOS_UNREACT = 'KUDOS_UNREACT',
  KUDOS_REPLY_CREATE = 'KUDOS_REPLY_CREATE',
  KUDOS_REPLY_UPDATE = 'KUDOS_REPLY_UPDATE',
  KUDOS_REPLY_DELETE = 'KUDOS_REPLY_DELETE',
  KUDOS_PIN = 'KUDOS_PIN',
  KUDOS_UNPIN = 'KUDOS_UNPIN',
  ONBOARDING_COMPLETE_ITEM = 'ONBOARDING_COMPLETE_ITEM',
  REQUEST_APPROVE = 'REQUEST_APPROVE',
  REQUEST_REJECT = 'REQUEST_REJECT',

  // Approval Delegations
  DELEGATION_CREATE = 'DELEGATION_CREATE',
  DELEGATION_REVOKE = 'DELEGATION_REVOKE',

  // HR - Admissão Digital
  ADMISSION_CREATE = 'ADMISSION_CREATE',
  ADMISSION_APPROVE = 'ADMISSION_APPROVE',
  ADMISSION_REJECT = 'ADMISSION_REJECT',
  ADMISSION_CANCEL = 'ADMISSION_CANCEL',
  ADMISSION_SIGN = 'ADMISSION_SIGN',

  // Sistema
  EXPORT = 'EXPORT',
  IMPORT = 'IMPORT',
  SYNC = 'SYNC',
  DUPLICATE = 'DUPLICATE',
  GENERATE = 'GENERATE',
  PAUSE = 'PAUSE',
  RESUME = 'RESUME',
  CANCEL = 'CANCEL',
  ACTIVATE = 'ACTIVATE',
  DEACTIVATE = 'DEACTIVATE',
  EXECUTE = 'EXECUTE',
  PREVIEW = 'PREVIEW',
  VALIDATE = 'VALIDATE',
  ENROLL = 'ENROLL',
  ADVANCE_STEP = 'ADVANCE_STEP',
  PROCESS_PENDING = 'PROCESS_PENDING',

  // AI & Analysis
  PREDICT = 'PREDICT',
  SENTIMENT_ANALYZE = 'SENTIMENT_ANALYZE',

  // Recruitment
  JOB_PUBLISH = 'JOB_PUBLISH',
  JOB_CLOSE = 'JOB_CLOSE',
  CANDIDATE_HIRE = 'CANDIDATE_HIRE',
  CANDIDATE_REJECT = 'CANDIDATE_REJECT',
  INTERVIEW_SCHEDULE = 'INTERVIEW_SCHEDULE',
  INTERVIEW_COMPLETE = 'INTERVIEW_COMPLETE',
  INTERVIEW_CANCEL = 'INTERVIEW_CANCEL',

  // Phase 6 / Plan 06-01 — Compliance Portaria 671
  COMPLIANCE_GENERATE = 'COMPLIANCE_GENERATE',
  COMPLIANCE_DOWNLOAD = 'COMPLIANCE_DOWNLOAD',
  COMPLIANCE_VERIFY_PUBLIC = 'COMPLIANCE_VERIFY_PUBLIC',
  ESOCIAL_SUBMIT = 'ESOCIAL_SUBMIT',

  // Phase 7 / Plan 07-01 — Dashboard Gestor
  PUNCH_BATCH_EXPORTED = 'PUNCH_BATCH_EXPORTED',
  PUNCH_MISSED_PUNCH_DETECTED = 'PUNCH_MISSED_PUNCH_DETECTED',
  PUNCH_DEVICE_STATUS_CHANGED = 'PUNCH_DEVICE_STATUS_CHANGED',
  PUNCH_APPROVAL_RESOLVED = 'PUNCH_APPROVAL_RESOLVED',

  // Phase 9 / Plan 09-01 — Antifraude Hardening (D-25, D-26)
  // NOTA: dívida técnica conhecida — schema Prisma `AuditAction` ainda não
  // tem esses 2 values. logAudit fará swallow do PrismaClientValidationError
  // até a próxima migration de sync (Decisions 04-04 / 06-02 / 07-01).
  // Plan 09-03/09-04 deve coordenar a sync TS↔Prisma quando o controller
  // de /hr/punch/audit for implementado.
  PUNCH_AUDIT_MARK_SUSPICION = 'PUNCH_AUDIT_MARK_SUSPICION',
  PUNCH_AUDIT_VIEW = 'PUNCH_AUDIT_VIEW',

  // Phase 10 / Plan 10-01 — Punch-Agent Biométrico (Pitfall 8 — sync com Prisma enum)
  AGENT_PAIRED = 'AGENT_PAIRED',
  BIO_ENROLLED = 'BIO_ENROLLED',
  BIO_MATCH = 'BIO_MATCH',
  AGENT_REVOKED = 'AGENT_REVOKED',

  OTHER = 'OTHER',
}
