/**
 * Deal Won event consumer.
 *
 * Auto-creates a draft Order when a deal is marked as won,
 * linking the order back to the deal for traceability.
 */

import type { DomainEvent, EventConsumer } from '../domain-event.interface';
import { SALES_EVENTS } from '../sales-events';
import type { DealWonData } from '../sales-events';

// Lazy logger to avoid @env initialization in unit tests
let _logger: {
  info: (obj: unknown, msg: string) => void;
  warn: (obj: unknown, msg: string) => void;
  error: (obj: unknown, msg: string) => void;
} | null = null;
function getLogger() {
  if (!_logger) {
    try {
      // eslint-disable-next-line @typescript-eslint/no-require-imports
      _logger = require('@/lib/logger').logger;
    } catch {
      _logger = {
        info: (obj, msg) => console.log(msg, obj),
        warn: (obj, msg) => console.warn(msg, obj),
        error: (obj, msg) => console.error(msg, obj),
      };
    }
  }
  return _logger!;
}

/**
 * Lazily load Prisma client for direct database access.
 * Uses prisma directly (not use cases) to avoid circular dependencies.
 */
function getPrismaClient() {
  const { prisma } = require('@/lib/prisma'); // eslint-disable-line @typescript-eslint/no-require-imports
  return prisma;
}

/**
 * Format a currency value as BRL string.
 */
function formatBRL(value: number): string {
  return new Intl.NumberFormat('pt-BR', {
    style: 'currency',
    currency: 'BRL',
  }).format(value);
}

export const dealWonOrderCreationConsumer: EventConsumer = {
  consumerId: 'sales.deal-won-order-handler',
  moduleId: 'sales',
  subscribesTo: [SALES_EVENTS.DEAL_WON],

  async handle(event: DomainEvent): Promise<void> {
    const data = event.data as unknown as DealWonData;
    const { dealId, customerId, value } = data;

    getLogger().info(
      { dealId, customerId, value, eventId: event.id },
      `[DealWonConsumer] Criando pedido rascunho para deal ganho #${dealId.slice(0, 8)}`,
    );

    try {
      const prismaClient = getPrismaClient();

      // 1. Find the deal with customer info
      const deal = await prismaClient.deal.findUnique({
        where: { id: dealId },
        include: { customer: true },
      });

      if (!deal) {
        getLogger().warn(
          { dealId, eventId: event.id },
          `[DealWonConsumer] Deal ${dealId} nao encontrado - pedido nao criado`,
        );
        return;
      }

      // 2. Create a draft order from the deal
      const createdOrder = await prismaClient.order.create({
        data: {
          tenantId: event.tenantId,
          customerId,
          channel: 'CRM',
          type: 'SALE',
          status: 'DRAFT',
          notes: `Gerado automaticamente do neg\u00f3cio ganho #${dealId.slice(0, 8)} (${formatBRL(value)})`,
          subtotal: value,
          total: value,
          metadata: {
            dealId,
            sourceEventId: event.id,
            autoGenerated: true,
          },
        },
      });

      // 3. Update the deal with the orderId reference
      await prismaClient.deal.update({
        where: { id: dealId },
        data: {
          metadata: {
            ...(typeof deal.metadata === 'object' && deal.metadata !== null
              ? (deal.metadata as Record<string, unknown>)
              : {}),
            orderId: createdOrder.id,
            orderCreatedAt: new Date().toISOString(),
          },
        },
      });

      getLogger().info(
        {
          dealId,
          orderId: createdOrder.id,
          total: formatBRL(value),
          eventId: event.id,
        },
        `[DealWonConsumer] Pedido rascunho ${createdOrder.id} criado para deal #${dealId.slice(0, 8)}`,
      );
    } catch (err) {
      getLogger().error(
        { dealId, eventId: event.id, error: err },
        '[DealWonConsumer] Falha ao criar pedido rascunho para deal ganho',
      );
      throw err; // Re-throw to trigger retry
    }
  },
};
