import type { FastifyInstance } from 'fastify';
import { createModuleMiddleware } from '@/http/middlewares/tenant/verify-module';

import { createFinanceEntryController } from './v1-create-finance-entry.controller';
import { updateFinanceEntryController } from './v1-update-finance-entry.controller';
import { deleteFinanceEntryController } from './v1-delete-finance-entry.controller';
import { getFinanceEntryByIdController } from './v1-get-finance-entry-by-id.controller';
import { listFinanceEntriesController } from './v1-list-finance-entries.controller';
import { registerPaymentController } from './v1-register-payment.controller';
import { cancelFinanceEntryController } from './v1-cancel-finance-entry.controller';
import { parseBoletoController } from './v1-parse-boleto.controller';
import { parsePixController } from './v1-parse-pix.controller';
import { checkOverdueController } from './v1-check-overdue.controller';
import { importPayrollController } from './v1-import-payroll.controller';
import { ocrExtractDataController } from './v1-ocr-extract-data.controller';
import { ocrUploadBatchController } from './v1-ocr-upload-batch.controller';
import { getLastSupplierEntryController } from './v1-get-last-supplier-entry.controller';
import { createBoletoForEntryController } from './v1-create-boleto-for-entry.controller';
import { emitNfeFromEntryController } from './v1-emit-nfe-from-entry.controller';
import { createPixChargeController } from './v1-create-pix-charge.controller';
import { payViaPixController } from './v1-pay-via-pix.controller';
import { createEntriesBatchController } from './v1-create-entries-batch.controller';
import { bulkPayEntriesController } from './v1-bulk-pay-entries.controller';
import { bulkCancelEntriesController } from './v1-bulk-cancel-entries.controller';
import { bulkDeleteEntriesController } from './v1-bulk-delete-entries.controller';
import { bulkCategorizeEntriesController } from './v1-bulk-categorize-entries.controller';
import { emailToEntryConfigController } from './v1-email-to-entry-config.controller';
import { processEmailToEntryController } from './v1-process-email-to-entry.controller';
import { calculateEntryRetentionsController } from './v1-calculate-entry-retentions.controller';
import { applyEntryRetentionsController } from './v1-apply-entry-retentions.controller';
import { listEntryRetentionsController } from './v1-list-entry-retentions.controller';
import { threeWayMatchController } from './v1-three-way-match.controller';

export async function financeEntriesRoutes(app: FastifyInstance) {
  app.addHook('preHandler', createModuleMiddleware('FINANCE'));

  app.register(getFinanceEntryByIdController);
  app.register(listFinanceEntriesController);
  app.register(createFinanceEntryController);
  app.register(createEntriesBatchController);
  app.register(updateFinanceEntryController);
  app.register(deleteFinanceEntryController);
  app.register(registerPaymentController);
  app.register(cancelFinanceEntryController);
  app.register(bulkPayEntriesController);
  app.register(bulkCancelEntriesController);
  app.register(bulkDeleteEntriesController);
  app.register(bulkCategorizeEntriesController);
  app.register(createBoletoForEntryController);
  app.register(createPixChargeController);
  app.register(payViaPixController);
  app.register(parseBoletoController);
  app.register(parsePixController);
  app.register(checkOverdueController);
  app.register(importPayrollController);
  app.register(ocrExtractDataController);
  app.register(ocrUploadBatchController);
  app.register(getLastSupplierEntryController);
  app.register(emitNfeFromEntryController);
  app.register(emailToEntryConfigController);
  app.register(processEmailToEntryController);
  app.register(calculateEntryRetentionsController);
  app.register(applyEntryRetentionsController);
  app.register(listEntryRetentionsController);
  app.register(threeWayMatchController);
}
