import { z } from 'zod';

export const updateAiConfigBodySchema = z.object({
  assistantName: z.string().max(64).optional(),
  assistantAvatar: z.string().nullable().optional(),
  personality: z
    .enum(['PROFESSIONAL', 'FRIENDLY', 'CASUAL', 'FORMAL', 'CUSTOM'])
    .optional(),
  customPersonality: z.string().nullable().optional(),
  toneOfVoice: z.enum(['NEUTRAL', 'WARM', 'DIRECT', 'ENTHUSIASTIC']).optional(),
  language: z.string().max(8).optional(),
  greeting: z.string().nullable().optional(),
  enableDedicatedChat: z.boolean().optional(),
  enableInlineContext: z.boolean().optional(),
  enableCommandBar: z.boolean().optional(),
  enableVoice: z.boolean().optional(),
  wakeWord: z.string().nullable().optional(),
  tier1Provider: z.string().max(32).optional(),
  tier2Provider: z.string().max(32).optional(),
  tier3Provider: z.string().max(32).optional(),
  selfHostedEndpoint: z.string().nullable().optional(),
  tier1ApiKey: z.string().nullable().optional(),
  tier2ApiKey: z.string().nullable().optional(),
  tier3ApiKey: z.string().nullable().optional(),
  canExecuteActions: z.boolean().optional(),
  requireConfirmation: z.boolean().optional(),
  maxActionsPerMinute: z.number().int().min(1).max(60).optional(),
  enableProactiveInsights: z.boolean().optional(),
  insightFrequency: z.string().max(16).optional(),
  enableScheduledReports: z.boolean().optional(),
  accessibleModules: z.array(z.string()).optional(),
});

export const aiConfigResponseSchema = z.object({
  tenantId: z.string(),
  assistantName: z.string(),
  assistantAvatar: z.string().nullable(),
  personality: z.string(),
  customPersonality: z.string().nullable(),
  toneOfVoice: z.string(),
  language: z.string(),
  greeting: z.string().nullable(),
  enableDedicatedChat: z.boolean(),
  enableInlineContext: z.boolean(),
  enableCommandBar: z.boolean(),
  enableVoice: z.boolean(),
  wakeWord: z.string().nullable(),
  tier1Provider: z.string(),
  tier2Provider: z.string(),
  tier3Provider: z.string(),
  selfHostedEndpoint: z.string().nullable(),
  tier1ApiKey: z.string().nullable(),
  tier2ApiKey: z.string().nullable(),
  tier3ApiKey: z.string().nullable(),
  canExecuteActions: z.boolean(),
  requireConfirmation: z.boolean(),
  maxActionsPerMinute: z.number(),
  enableProactiveInsights: z.boolean(),
  insightFrequency: z.string(),
  enableScheduledReports: z.boolean(),
  accessibleModules: z.array(z.string()),
});
